magit.el

Hello,
Not sure the doc string/emplacement is adequate, please comment.

Add apply/format patches to help menu

---

magit-utils.el

`ido-completing-read` is not suitable as a replacement for
`completing-read`, because it lacks essential features and
has bugs.  Instead use the wrapper `completing-read-ido`
from the `ido-ubiquitous` package.

use completing-read-ido from the ido-ubiquitous package

---

magit-process.el

This is related to #1791. 
CC:  @halbtuerke

Use cl-lib version instead of cl.el

---

.travis.yml

Same as #1794, but on `master`.
replace/ close #1794

.travis.yml: set EMACSBIN in calls to make

---

magit.el

* magit.el (magit-insert-repo-header): Prettify.

magit.el (magit-insert-remote-header): Fixup.

---

lisp/magit.el

And fix interactive form.
see #1913.

magit-copy-buffer-thing-as-kill: do the copy

---

lisp/magit-ediff.el

See #1963 and c18264374d1a42edfc7e781a8c7fe39d78b4ea1b.
Please test and comment.

Add new hook magit-ediff-quit-hook

---

lisp/magit-diff.el
lisp/magit-log.el
lisp/magit-mode.el
lisp/magit-popup.el
lisp/magit-sequence.el
lisp/magit-stash.el
lisp/magit.el

Support for changing diff arguments already existed, but was rather broken.

Allow changing the log and diff arguments used in a buffer

---

lisp/magit-log.el

`git log --graph --max-count=N` calculates the graph for the complete
history; the `--max-count=N` only affects the output phase.
`git log --graph HEAD~N..HEAD` only calculates the graph for
HEAD~N..HEAD but the graph is not the same; commits that are reachable
from HEAD but do not descend from HEAD~N will appear as root commits.
Address this by using `--max-count` and REV~M..REV to together when
possible.  More precisely do so when showing the log for a single rev
in the log buffer.  M is usually twice as large as N but at least 1024,
which greatly reduces the risk of the graphs for REV~M..REV and REV to
differ.
In the status buffer also limit the range for the log section inserted
by `magit-insert-recent-commits`, but without avoiding that non-root
commits appear as root commits …

avoid `git log --graph' inefficiency

---

lisp/magit-git.el
lisp/magit-process.el

By default, Cygwin and MSYS2 executables attempt to expand globs when
called by a program other than a Unix shell.  The intent is to provide
globbing when, for instance, using Cygwin's grep from the Windows
command prompt.
However, this causes problems when calling the Cygwin or MSYS2 git from
Magit in a native Windows Emacs.  The solution is to detect this
behavior and, when present, add "noglob" to the "CYGWIN" and "MSYS"
environment variables to disable it.
See https://cygwin.com/cygwin-ug-net/using-cygwinenv.html
Fixes #2246.

Use the "noglob" option on Cygwin and MSYS2

---

lisp/magit-log.el

Show update date in reflog margin, don't show author name

---

lisp/magit.el

Revision stack tweaks

---

lisp/git-commit.el
lisp/magit-git.el

```
Rely on the output from mount to tell us how to map cygwin paths into
native Windows paths.
This is also needed in git-commit; avoid a hard dependency on magit by
only loading magit-git in the case where we receive a bad path to
foo_EDITMSG (and falling back to the standard "/cygdrive" prefix if we
fail to load).
```
---
fix #2317
replace/ close #2324

handle custom cygwin mounts

---

Documentation/RelNotes/2.4.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-remote.el

But don't add these commands to the popup by default.

Restore magit-push-implicitly, add magit-push-to-remote

---

README.md

Fix capitalization of GitHub in README

---

lisp/magit-utils.el

Change Helm completion function

---

Documentation/RelNotes/2.6.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-ediff.el

Stash ediffing

---

Documentation/RelNotes/2.6.1.txt
lisp/git-commit.el

git-commit-propertize-diff fixes 

---

Documentation/RelNotes/2.7.1.txt
lisp/magit-bisect.el

support showing and copying bisect-output section

---

Documentation/RelNotes/2.7.1.txt
lisp/git-rebase.el
lisp/magit-diff.el
lisp/magit-sequence.el

Use `core.commentchar` in Git Rebase mode

---

Documentation/RelNotes/2.7.1.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit.el

I probably won't get around to documenting and merging this any time soon.  But I think this is quite usable already and so I make it available in its current form. Note that there might be breaking changes - I have thrown this together rather quickly.

magit-list-repositories: new command

---

Documentation/RelNotes/2.7.1.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-log.el

add magit-log-move-to-parent command

---

Documentation/RelNotes/2.7.1.txt
lisp/magit-submodule.el

List submodules using a tabulated-list-mode buffer

---

lisp/git-commit.el

```
Add a function to font-lock-extend-region-functions to correctly
identity the multiline git-commit-summary-regexp to font-lock, as
suggested in `(elisp) Multiline Font Lock'.  This causes the
git-commit-nonempty-second-line face to be applied immediately, instead
of having to run font-lock-fontify-block manually to trigger it.
```
Fixes the first issue mentioned in #2772.

git-commit: Fix highlighting of second line

---

lisp/magit-git.el
t/magit-tests.el

This is a new version of #2670, with fixes for all the issues that came up since then (& tests for those issues).

cache git config more aggressively (v2)

---

Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el
lisp/magit-ediff.el
lisp/magit-git.el
lisp/magit-sequence.el

Improve magit-diff-visit-file

---

Documentation/RelNotes/2.9.0.txt

Documenting #2834 in release notes.

Document improved hunk-refining performance in release notes

---

Documentation/RelNotes/2.9.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/git-rebase.el

git-rebase: support documented scroll-down behavior

---

lisp/magit-wip.el

https://github.com/magit/magit/issues/2881

Fix magit-wip-after-apply-mode lighter typo

---

lisp/magit-mode.el

Abbreviate default directory for buffer listings

---

Documentation/RelNotes/2.10.4.txt
lisp/magit-remote.el

I have a use-case for this, and others probably do too.  Thanks!

Add defcustom to toggle fetching when adding a remote

---

Documentation/RelNotes/2.10.4.txt
lisp/magit.el

magit-shell-command: use a shell

---

Documentation/RelNotes/2.10.4.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-process.el
lisp/magit.el

Use a shell in magit-git-command et al

---

lisp/magit-branch.el
lisp/magit-git.el

See #3058 for prior discussion.

Confirm branch deletion in some additional cases

---

Documentation/RelNotes/2.11.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el
lisp/magit-log.el
lisp/magit-mode.el

[resurrection and reroll of #2146]

magit-use-sticky-arguments: new option

---

lisp/magit-apply.el
lisp/magit-ediff.el
lisp/magit-git.el
lisp/magit-obsolete.el
lisp/magit-repos.el
lisp/magit-stash.el

Remove misbehaving magit-unstaged-files; maybe rename magit-modified-files

---

default.mk
lisp/Makefile
lisp/git-rebase.el
lisp/magit-diff.el
lisp/magit-imenu.el
lisp/magit-log.el
lisp/magit-process.el
lisp/magit-refs.el
lisp/magit-repos.el
lisp/magit-status.el
lisp/magit-submodule.el
lisp/magit.el

* Implement [@kyleam's suggestions](https://github.com/magit/magit/issues/3022#issuecomment-302590319) on current imenu support.
* Also add support in `git-rebase-mode`

More imenu support

---

Documentation/RelNotes/2.11.0.txt
lisp/magit-branch.el
lisp/magit-diff.el
lisp/magit-git.el

Please see commit messages.
Re: #3098

Improve handling of ambiguous refnames

---

lisp/magit-git.el

```
Every 'git-name-rev --refs=PATTERN' instance in Magit has the
intention of restricting the results to refs within a particular
namespace ('refs/heads/', 'refs/remotes/', and so on).  This approach
has false positives, though, because git-name-rev matches PATTERN
against any part of the ref name, not only the beginning.  magit-wip's
names are frequent offenders (e.g., 'refs/wip/wtree/refs/heads/').
9ab6d554 (magit-rev-name: anchor the ref pattern by default,
2017-06-20) eliminated these non-namespace matches by automatically
tacking on an '--exclude=*/PATTERN', but we reverted it in b8d55867
because the --exclude option wasn't added until Git v2.13.0.
Instead let's discard git-name-rev's choice if it includes the
namespace as a substring.  Because the substring match could result
from …
```

magit-rev-name: treat 'refs/<subdir>/*' as a namespace

---

lisp/magit-status.el

Continued from #3096. This time I did see that having `magit--refresh-cache` non-nil around the call to `magit-init` broke it (cf https://github.com/magit/magit/pull/3096#issuecomment-307443148).

magit-status: Use magit--refresh-cache

---

Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el

Don't use log's file restriction with --follow

---

Documentation/RelNotes/2.11.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el

Please see the commit messages.

Generalize magit-revision-toggle-file-filter to all diffs

---

Documentation/RelNotes/2.11.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-obsolete.el
lisp/magit-section.el
lisp/magit-status.el
lisp/magit-submodule.el

Please see the commit messages.

Speedup inserting module sections

---

Documentation/RelNotes/2.12.0.txt
lisp/magit-commit.el
lisp/magit-log.el
lisp/magit-sequence.el

Teach fixup commands to warn about merge commits and unreachable commits

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-blame.el
lisp/magit-files.el

Support reverse blaming

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
lisp/magit-mode.el

Needed for many of the features listed in vermiculus/magithub#72.

Custom buffer lock values

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-branch.el
lisp/magit-popup.el
lisp/magit-remote.el

Allow setting relevant variables from remote popup

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el
lisp/magit-files.el
lisp/magit-sequence.el

Add basic commands for saving and applying plain patch files

---

Documentation/RelNotes/2.12.0.txt
lisp/magit-log.el
lisp/magit-obsolete.el
lisp/magit-status.el

Always show recent commits and maintain visibility state

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-branch.el

Add new command magit-branch-checkout

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el
lisp/magit-git.el

Linkify hashes in commit messages

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-branch.el
lisp/magit-git.el
lisp/magit-obsolete.el
lisp/magit-popup.el
lisp/magit-stash.el
lisp/magit-utils.el
lisp/magit.el

Closes #3220.
Closes #2926.
Closes #2916.

Add option to decouple confirmation and completion

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-git.el
lisp/magit.el

Abbreviate log decorations by merging names of related branches

---

lisp/magit-git.el
lisp/magit-sequence.el

Properly deal with merges when cherry-picking

---

Documentation/magit.org
Documentation/magit.texi

Replace `b p` (the keys to configure push remote) with `b R` and `b r`.

manual: update pull-request key bindings

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el
lisp/magit-mode.el
lisp/magit-obsolete.el
lisp/magit-section.el
lisp/magit-stash.el
lisp/magit-status.el

Improve section visibility cache and allow customizing initial visibility 

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
Documentation/magit.texi
lisp/magit-git.el
lisp/magit-submodule.el

@npostavs This is still very much work-in-progress and completely untested and undocumented, but gives a pretty good idea of I intend to do. This succeeds your earlier drafts; do you agree this is the way forward?

Improve module commands

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
lisp/magit-git.el
lisp/magit-merge.el

Add commands to absorb (merge and remove) a branch

---

Documentation/RelNotes/2.12.0.txt
Documentation/magit.org
lisp/magit-sequence.el

Add commands to move cherries between branches

---

Documentation/RelNotes/2.12.0.txt
lisp/magit-log.el
lisp/magit-margin.el
lisp/magit-refs.el

The interesting stuff is in acea27520c4c3cbcbca1fd9a743a6ef369a26f5f.

Refactor refs buffers

---

Documentation/magit.org
Documentation/magit.texi
lisp/git-commit.el
lisp/magit-wip.el

Merge the real branch into the wipref

---

lisp/magit-sequence.el

magit-perl-executable: New variable

---

Documentation/RelNotes/2.90.0.org
Documentation/magit.org
Documentation/magit.texi
lisp/magit-diff.el
lisp/magit-log.el
lisp/magit-refs.el
lisp/magit-section.el
lisp/magit-stash.el
lisp/magit-status.el

v2 of #3505 (see also #3308 for initial suggestion).

magit-describe-section for users

---

lisp/magit-mode.el
lisp/magit-status.el

Only jump to commits when first creating the status buffer

---

lisp/magit-diff.el
lisp/magit-git.el
lisp/magit-sequence.el
lisp/magit-status.el
lisp/magit-submodule.el

Allow ignoring submodules

---

.mailmap
Documentation/AUTHORS.md
Documentation/magit.org
Documentation/magit.texi

I noticed some typos and ambiguity in the docs concerning color control sequence output. Thought I would clean it up while I had it in front of me.

Edit FAQ wording concerning handling of color

---

lisp/magit-mode.el

Fixes #3330 (see commit message).

magit-display-buffer: Don't reselect the same frame

---

lisp/git-commit.el
lisp/magit-apply.el
lisp/magit-commit.el
lisp/magit-mode.el

See the commit messages and #3496. https://github.com/magit/with-editor/commit/f69daaf0acd9096bd3758fdc73a34b1a48d9c4f1 is also related.

Add some frequently requested hooks

---

lisp/magit-apply.el
lisp/magit-blame.el
lisp/magit-bookmark.el
lisp/magit-branch.el
lisp/magit-commit.el
lisp/magit-diff.el
lisp/magit-extras.el
lisp/magit-files.el
lisp/magit-git.el
lisp/magit-gitignore.el
lisp/magit-imenu.el
lisp/magit-log.el
lisp/magit-margin.el
lisp/magit-merge.el
lisp/magit-mode.el
lisp/magit-patch.el
lisp/magit-process.el
lisp/magit-push.el
lisp/magit-refs.el
lisp/magit-repos.el
lisp/magit-section.el
lisp/magit-sequence.el
lisp/magit-stash.el
lisp/magit-status.el
lisp/magit-submodule.el
lisp/magit-utils.el
lisp/magit-wip.el
lisp/magit.el

If/when-let are macros that can be expanded at compile time rather
than at run time

Require subr-x at compile time

---

Documentation/RelNotes/2.91.0.org
lisp/magit-commit.el
lisp/magit-sequence.el

--keep-empty commits when autosquashing

---

lisp/magit-status.el

Buried was misspelled.
=================================================================
Use a dedicated feature branch
=================================================================
Please use a dedicated feature branch for your feature request, instead of asking us to merge "your-fork/master" into the "origin/master".  The use of dedicated branches makes it much more convenient to deal with pull-requests, especially when using Magit to do so.
If you were about to open a pull-request asking us to merge your version of "master", then see [1] for instructions on how to quickly fix that and some information on why we ask you to do so.
Additionally we ask you to allow us to push to the branch you want us to merge.  We might want to push additional commits and/or make minor changes. …

Fix spelling error in magit-status.el

---

Documentation/RelNotes/2.91.0.org
Documentation/magit.org
Documentation/magit.texi
lisp/git-rebase.el
lisp/magit-diff.el
lisp/magit-sequence.el

The PR supersedes (and includes two commits from) #3711.

Support for  --rebase-merges, v2

---

.travis.yml
Makefile
default.mk
lisp/Makefile
lisp/magit-core.el
lisp/magit-git.el
lisp/magit-libgit.el
lisp/magit-mode.el
lisp/magit-utils.el

Description coming soon. (Need to coordinate changes to three repositories.)

Basic libgit support

---

Documentation/magit.org
Documentation/magit.texi

update documentation on automatic buffer refresh

---

Documentation/magit.org
Documentation/magit.texi
lisp/magit-clone.el
lisp/magit-mode.el
lisp/magit.el

Replace the single clone command with a transient prefix with several suffixes

---

lisp/magit-diff.el
lisp/magit-git.el
lisp/magit-log.el
lisp/magit-utils.el
t/magit-tests.el

For https://github.com/magit/magit/pull/3886#issuecomment-523511418
I think this should work, but it's getting late enough that I might
have missed something silly.

magit--add-face-text-property

---

lisp/magit-log.el

This PR makes it possible to pass `--tags=<a pattern>` to `git log`.

List matching tags

---

Documentation/RelNotes/2.91.0.org
lisp/magit-extras.el

A modest attempt to contribute something small to this great package. 
Any and all comments, critique, and tips on improvements very much welcomed.

magit-extras: New option: magit-revision-format

---

Documentation/magit.org
lisp/magit-tag.el

https://github.com/magit/magit/issues/4074

Add support for pre-release SemVer versions

---

Documentation/magit-section.org
Documentation/magit-section.texi
Documentation/magit.org
Documentation/magit.texi
lisp/magit-reset.el

I use `git reset --keep` a lot from the command line when I have some uncommitted changes that I realize ought to be applied to a different branch.  How about something like this in magit?
I'd welcome any suggestions that would make the wording clearer.

Add support for git reset --keep

---

lisp/magit-git.el

In certain circumstances, the calling buffer's process-environment may
be lost when using `with-temp-buffer`, so we explicitly prevent that
from happening in order to ensure that `git` will be invoked as
expected.
See #4160 for more information.

magit-git: always use caller's process-environment when invoking git

---

lisp/magit-diff.el

=================================================================
Use a dedicated feature branch
=================================================================
Please use a dedicated feature branch for your feature request, instead of asking us to merge "your-fork/master" into the "origin/master".  The use of dedicated branches makes it much more convenient to deal with pull-requests, especially when using Magit to do so.
If you were about to open a pull-request asking us to merge your version of "master", then see [1] for instructions on how to quickly fix that and some information on why we ask you to do so.
Additionally we ask you to allow us to push to the branch you want us to merge.  We might want to push additional commits and/or make minor changes.  Please make sure the box …

Remove duplicate definition of ‘magit-buffer-value’

---

lisp/magit-files.el

Gives magit-file-rename similar behavior to rename-file when newname is a directory name by moving the source file into the destination directory.
Closes #4122

magit-file-rename: Allow destination directory as second argument

---

lisp/git-commit.el

git-commit: Fix docstring

---

lisp/magit-sequence.el

When "magit-rebase-remove-commit" (r k) is called, it replaces the line with
"noop" followed by a commented-out version of the original "pick" command on a
separate line. However, the comment character is hardcoded to "#", which does
not work as expected when the "core.commentChar" option is set to something
other than "#" in .gitconfig files.
This change overrides the value of "core.commentChar" when
"magit-rebase-interactive-1" is called within "magit-rebase-remove-commit", so
that the rebase operation can properly delete the commit, and further ensures
that it set when "magit-log-select" called in "magit-rebase-interactive-1".
(Formerly):
~When "magit-rebase-remove-commit" (r k) is called, it replaces the line with~
~"noop" followed by a commented-out version of the original "pick" …

magit-rebase-remove-commit: override core.commentChar

---

lisp/magit-files.el

Fix #4286 
1. `magit-update-index` calls `make-temp-file` to create a temporary file to store the edited buffer for the index.
2. [`make-temp-file`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Unique-File-Names.html#index-make_002dtemp_002dfile) create a file relative to the special variable [`temporary-file-directory`](index-temporary_002dfile_002ddirectory-1)
3. The special variable `temporary-file-directory` is not automatically set by Emacs/TRAMP, so it points to the local machine's TMPDIR/TMP/TEMP directory. Thus, `make-temp-file` creates a file on the local machine.
4. `magit-update-index` thus writes the new index contents to a local file.
5. `magit-update-index` calls `git hash-object ... -- /tmp/indexXXX` on the remote machine, but of course the remote machine does …

magit-update-index: make it work over TRAMP

---

Documentation/magit.org
Documentation/magit.texi
lisp/magit-bisect.el
lisp/magit-diff.el
lisp/magit-extras.el
lisp/magit-git.el
lisp/magit-log.el
lisp/magit-process.el
lisp/magit-status.el
lisp/magit.el

...and absolute path on macOS.

Use separate option for remote git executable

---

lisp/magit-mode.el

Add a word to fix grammar nit.

Add missing word to docstring

---

Documentation/RelNotes/3.4.0.org
lisp/git-rebase.el

- Add new face to customize look of "pick/reword/..." actions
- Fix group of git-rebase-comment-heading face

git-rebase.el: Add new face to customize look of rebase actions

---

Documentation/magit.org
Documentation/magit.texi

Evil repository is no longer available on Bitbucket.

manual : Fix Evil URL

---

lisp/magit-pull.el

Support equivalent functionality to `git pull --ff-only` .

Support pull --ff-only

---

lisp/magit-bisect.el
lisp/magit-branch.el
lisp/magit-diff.el
lisp/magit-fetch.el
lisp/magit-git.el
lisp/magit-sequence.el
lisp/magit-status.el
lisp/magit-submodule.el
lisp/magit-utils.el
lisp/magit-wip.el
lisp/magit.el

@kyleam what do you think?
Also, how many translations did I mess up?

Resist the Jedi

---

docs/magit.org
docs/magit.texi

Minimal change in documentation to change the description of the remote.NAME.pushurl variable

Minimal change correcting description to remote.NAME.pushurl variable

---

docs/magit.org
docs/magit.texi
lisp/magit-diff.el

Hope little edits like these aren't considered a nuisance, if so feel free to close, just noticed it while I was reading and figured I'd contribute back this tiny fix.
Thank you for working on Magit!

Fix doc typo

---

lisp/magit-git.el
lisp/magit-reset.el

Fix two typos

---

lisp/git-commit.el

`git-commit-post-finish-hook` is not run until the new commit has been created. If Git takes more than 1 second to do so, the hook isn’t run.
Whereas a 1 second timeout seems reasonable for most use cases, there are use cases where a greater time is desirable.
For ex., when `git` is configured to sign commits with GnuPG, the user might be interactively prompted to enter the passphrase of the GnuPG private key.
If the user takes more than 1 second to type their passphrase, the hook isn’t run.
In order to address such use cases, the new variable `git-commit-timeout` allows to tune the value of this timeout.

git-commit-timeout: New variable

---

lisp/magit-base.el
lisp/magit-libgit.el
lisp/magit-section.el

Arguably a trivial change, but nevertheless my first PR to Magit ;)

Remove unnecessary Compat requires

---

.github/dependabot.yml

This adds a daily check that GitHub Actions in workflows are up-to-date using Dependabot.
More information here:
https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file
https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Keep GitHub Actions up-to-date with Dependabot

---

docs/magit.org
docs/magit.texi

There are 7 equal characters <, >, =, that divide branch changes.

patch: Update manual

---

lisp/magit-apply.el
lisp/magit-base.el
lisp/magit-blame.el
lisp/magit-branch.el
lisp/magit-commit.el
lisp/magit-diff.el
lisp/magit-git.el
lisp/magit-log.el
lisp/magit-remote.el
lisp/magit-sequence.el
lisp/magit-stash.el
lisp/magit-submodule.el
lisp/magit-tag.el

Follow-up for #4905.
Implements the change described at https://github.com/magit/magit/discussions/4905#discussioncomment-5379339.

magit-branch-delete: Improve "also on remote?" prompt with >1 ref

---

test/magit-tests.el

Adds one test for a few UI commands. This would automatically catch the failure #5009 and of course would catch any other similar issues that might accidentally be introduced in the future.
Of course the tests might start failing simply because UI is changed, but that's how test works: you get alerted that "something is not as expected anymore" and then you decide if it is a bug and you need to fix something, or it is actually _not_ a bug and the test should be updated because the expectation have changed.

Basic UI tests; would catch the bug in commit 1ab107a7

---

lisp/git-commit.el

It is suggested several places on the internet to use a git commit template, for instance
[here](https://gist.github.com/lisawolderiksen/a7b99d94c92c6671181611be1641c733). These often include a header comment:
This change ensures that headers are inserted after this leading comment, instead of above it.

git-commit: Ignore leading comment when inserting headers

---

lisp/git-commit.el

I'm sorry if this is in any way botched. I'm very far from being a wizard of elisp.
---
With commit.verbose set to true, a special line will be added to the commit message. All content below this will be ignored by git. This line is defined [as cut_line in wt-status.c](https://github.com/git/git/blob/3e0d3cd5c7def4808247caf168e17f2bbf47892b/wt-status.c#L38-L39). To be meta: git prepares the following buffer for this branch's commit:
```
git-commit: Add handling for the cut_line constant
With commit.verbose set to true, a special line will be added to the
commit message. All content below this will be ignored by git.
This line is defined as cut_line in wt-status.c:
https://github.com/git/git/blob/3e0d3cd5c7def4808247caf168e17f2bbf47892b/wt-status.c#L38-L39
I noticed that, for exceptionally …
```

git-commit: Add handling for the cut_line constant

---

lisp/magit-log.el

Signed-off-by: Park Zhou <ideapark@petalmail.com>

magit-log.el: Fix typo

---

lisp/magit-wip.el

Signed-off-by: Park Zhou <ideapark@petalmail.com>

magit-wip.el: Fix typo

---

docs/magit.org
docs/magit.texi

Fix minor typos

---

docs/magit.org
docs/magit.texi

Fixed a minor pluralization typo

Fix minor typo

---

docs/magit.org
docs/magit.texi
lisp/magit-status.el

I believe the documentation was wrong so I fixed it.

magit-status-show-untracked-files: Fix documentation
