- magit-diff.el
- magit-section.el
This seems to be the simplest approach to avoid needlessly re-refining an already refined hunk. See #1581.
> magit-diff-refine-hunk: avoid re-refining already refined hunks

- magit.el
Was getting `Wrong type argument: bufferp, nil` when calling `magit-git-command` before any other git-running commands.
eg:
`emacs -Q -L . -L ../dash/ -l magit -f magit-status --eval '(magit-git-command "status" default-directory)'`
> magit-git-command: create process buffer if needed

- magit-blame.el
Currently a lighter for blame-mode does not appear in the mode-line because the lighter variable is quoted.
> Do not quote magit-blame-mode-lighter

- magit-git.el
Add '--cached' flag to restricted 'git diff-index' output to staged
files.
> magit-staged-files: Restrict to staged files

- magit-git.el
I came across this issue via  `magit-blame`, which errors out on my Windows box at work. I believe it only affects people using a W32 build of Emacs but with a shell and git from Cygwin, which I suspect is rare. As such, I think it would be fair to consider it low priority and wait on until after the release if you see any issues here.
The cause of the error is that  `magit-file-relative-name` ends up comparing the lengths of `"c:/path/to/repo/file.el"` (the file name, from Emacs) and `"/path/to/repo"` (the repo dir, from git), so the result is `"o/file.el"` (two extraneous characters at the front).
This commit fixes it by calling `expand-file-name` on the repo dir from git, which ensures it has the leading drive letter, like the file.
It works for me without issue on Windows, Linux, and …
> magit-file-relative-name: fix for W32 with Cygwin

- magit-blame.el
```
If view-read-only is set to `t', magit-blame-mode will turn it on when
it calls read-only-mode. To stop view-mode from shadowing
magit-blame-mode's keybindings, ensure that magit-blame-mode's entry in
minor-mode-map-alist precedes view-mode's.
```
fix #1780.
> magit-blame-mode: shadow view-mode bindings

- magit-apply.el
The (mapcar #'magit-section-value) call was dropped in
d0e04a140d4042976a1d654a45670eea24b54669.
> magit-reverse-files: pass file names to prompt

- README.md
- magit-pkg.el
- magit.el
and if these dependencies are not satisfied complain at startup.
This will force some users to finally update. I am sorry for the inconvenience, but the cost of supporting older versions is getting to high.
This already is a compromise. I would have preferred to update to `24.4` and `2.*.*`. The former can be delayed until we update to nest release `25.1` (which will provide some very welcome additions for the seasoned elisper). Updating to `2.0.0` would have been nice, because that's when the defaults for pushing changed in Git, but that can be delayed until Magit itself gets the next pushing remake *and* `2.*.*` is available for MS Windows (why is that lagging behind so much?!).
> Require at least Git-1.9.4 and Emacs-24.2

- magit-blame.el
Hi, so I know Magit is in feature freeze, but I have a small bug fix for the `next` branch. I would
consider it a bug fix anyway:
If the user has turned on `global-auto-revert-mode`, and then does a `magit-blame`, the user will
start getting the message "Reverting (buffer) inhibited due to magit-blame-mode" every few seconds
(depending on the value of `auto-revert-interval`). This seems pretty spammy to me. It's especially
annoying when you are trying to type in the minibuffer, and this keeps popping up.
So could we remove this message? My opinion is that it does more harm than good. The original author meant well I'm sure, but I'm guessing they didn't use `global-auto-revert-mode`, or perhaps their `auto-revert-interval` is much higher then mine.
> don't spam "revert inhibited" in blame mode

- magit-utils.el
- magit.el
Fixes #1781.
Add new command `magit-branch-unset-upstream` to
avoid a complication, with the completion DEFAULT.
> use ido-completing-read+ for all Ido completion

- README.md
There is a missing `.` from the path to add to the `.emacs` as compared to the directions in the previous code blocks.
> DOC : Correct load path in install directions

- Makefile
If the ELPA_DIR is a link to another directory, ``dash`` etc were not found.  With the ```-L``` option find succeeds again.  I cannot think of any drawbacks this has, since emacs finds the library one way or the other.
> Makefile: follow links in finding libraries

- magit-mode.el
- magit-process.el
- magit.el
It's now possible to always be asked before buffers are reverted, or to do the reverts asynchronously.
The old mode `magit-auto-revert-mode` is replaced with a new non-boolean option `magit-revert-buffers`. The default value is `usage` which behaves like enabling the mode used to do, except that it shows an annoying message at the end with usage information. This let's us keep the intended behavior (but forces us to disable the usage information) while at the same time it avoids killing puppies.
This addresses #1809, #1807, #1803, and #1783; and replaces older approaches to adress these issues.
> Give users more control over buffer reverts

- Makefile
cygwin make passed cygwin paths to the emacs binary.  As a result, the library paths were not effective and autoloads could not be built.
This change makes magit's Makefile translate the paths in question, such that it builds properly on cygwin with NTEmacs.  It does not affect any non-cygwin system at all.  I did not test with cygwin's Emacs, but cygwin-built binaries generally can handle the mixed dos-drive-letter path notation as command-line arguments.
> Makefile: make paths work on cygwin with NTEmacs

- magit-diff.el
Check passed rev rather than master.
----
Just out of curiousity, in what circumstances did the previous check (fc3355a25af4cf88aa4b9825ee1901b0d901427c) fail?
> magit-show-commit: Fix commit check

- magit-diff.el
- magit-mode.el
- magit-section.el
"therefor" means "for or in exchange for that or this; for it", while "therefore" indicates logical consequence.
Thanks for Magit!
> therefor -> therefore

- lisp/magit-blame.el
Because Magit requires Emacs 24.4 and 'read-only-mode' was introduced at Emacs 24.3.
> Remove needless condition

- lisp/magit-log.el
- lisp/magit.el
Includes @steabert's improved regexp (see #1945).
Not using `--color` by default is my idea. Here too the problem likely is an inefficient regexp, but it's out of our control, and probably not as easily fixable. I have chosen to not color graphs by default, because speed is important and many users who miss the colors should be able to spot that `--color` is now available from the log popup. Also gives them a change to learn how to set default arguments from popups.
Any comments or suggestions?
Looks like there's soon going to be a `2.2.0` release.
Off-topic: @steabert you might want to associate the email address used when creating that commit with your github account.
> Speedup log by improving regexp and not using --color

- lisp/magit-diff.el
* Replace error with user-error.
* Reduce the message down to the common problem.  In the case of a
detached HEAD, which cannot have an upstream branch, the problem is
still that an upstream branch is not set.
> magit-diff-{unpushed,unpulled}: Update error calls

- lisp/magit-log.el
Fix spliced list introduced in 5a974ff6153f15311865b34bf1eaaeea5277e48f.
> magit-log-read-revs: Fix splicing

- lisp/magit-popup.el
Let these functions handle :action, :option, and :switch as
documented. The plural versions :actions, :options, and :switches are
still accepted.
---
context: https://github.com/magit/magit/pull/2041#issuecomment-120403699
> magit-{define,change,remove}-popup-key: singular type

- lisp/magit-sequence.el
Replica of the magit-rebase-autosquash fix from commit
f1afebf6b6e6128c701f87f6bfa3d9ffca938de3. See #2011.
> magit-rebase-unpushed: start from merge-base

- lisp/magit-diff.el
re: the second commit
When point is on the file or hunk header, I think it is more useful to
go to the first changed line rather than the first context line.
Thoughts?
> Hunk file posititioning

- lisp/magit-remote.el
Invoking magit-clone from /home/user/subdir with a request to clone a
repo into ~/subdir/repo results in a repo in
/home/user/subdir/~/subdir/repo.
Expand the directory name to an absolute path before passing to git-clone.
> Make magit-clone expand relative file names.

- lisp/git-commit.el
- lisp/magit-diff.el
- lisp/magit-popup.el
- lisp/magit.el
- lisp/with-editor.el
Usually building a new version of Magit does not require a clean environment (one in which no older version of Magit has been loaded yet). But when updating from `v1.*` to `v2.*` then it is required. Unfortunately many users who get Magit from Melpa never saw the update instructions, which explain that they have to do the uninstall-restart-reinstall dance.
That's not their fault because when they updated to `>=20150701` there was nothing that indicated that this would be different from previous updates. Likewise it's not the fault of the Melpa maintainers, because they are not responsible for `package.el` itself. It's nobodies fault, but we still have to fix it - I've had it with those "impossible bugs" where the user and the code don't agree about what can possibly happen.
So I have …
> depend on async to guarantee untainted builds

- lisp/magit-git.el
- t/magit-tests.el
This is intended to be merged before v2.2.2 is released.
> magit-toplevel: always follow links to repo subdirectories

- Documentation/RelNotes/2.2.2.txt
- lisp/magit-wip.el
Return nil if the reflog for WIPREF does not exist to prevent 'git log'
from failing on the unknown revision, resulting in magit-wip-log showing
an empty log.
> magit-wip-log-get-tips: ignore non-existent refs

- Documentation/RelNotes/2.3.0.txt
- lisp/magit-mode.el
Restoring the previous window configuration often means restoring a configuration we are no longer interested in. This is a better compromise between `quit-window` and restoring the configuration. But it might still have to be refined a bit.
> Quit window without restoring previous window configuration

- Documentation/RelNotes/2.3.0.txt
- lisp/magit-mode.el
- lisp/magit-section.el
As explained in the doc-string of that option, I *strongly* urge user
to *not* change the value of this option.  Re #2085, #2063, tweets, and
https://www.reddit.com/r/emacs/comments/3bt2nh/magit_v210_released/cstul4y.
> magit-keep-region-overlay: new option

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit.el
These are the broken implementations which were removed in cbb8c94aa8075770e3a56020688b6abc3d03f25b. I did not get around to implement non-broken ones yet.
> New commands magit-branch-spinoff and magit-branch-reset

- Documentation/RelNotes/2.3.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit.el
This allows navigating blobs similar to how `git-timemachine` does it. From a buffer visiting a tracked file use `C-c p` to go to the latest blob for that file, then `p` and `n` to navigate between blobs. Unlike `git-timemachine` which uses a some sort of session and displays all blobs in the same buffer, this simple implementation uses a separate buffer for each blob and there is no command to quit the session (i.e. kill all the created buffers). Therefore it is better to move "forward" using `q` instead of `n`, as the former kills the currently visited blob.
> Basic blob navigation

- lisp/magit-log.el
When the entire ancestry path is being shown, forming the log revision
as "M~N..M" loses the earliest commit (M~N).  Extending to N+1 will
error because it refers to an unknown revision.  Pass the non-range
revision instead.
> magit-log-refresh-buffer: don't drop first commit

- lisp/with-editor.el
When running `with-editor-debug` on Windows a few places threw an error. Although the shell-quote thing, I don't quite understand how that could ever have worked even on non-Windows platforms: `call-process`  shouldn't work with shell quoted arguments, right?
> Fixes for with-editor-debug (mostly for Windows)

- Documentation/RelNotes/2.3.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-bisect.el
- lisp/magit-diff.el
- lisp/magit-log.el
- lisp/magit-stash.el
`-L` was supported until 9c2b8a87ef38122f733fda973be7d19766d7b955. I'll comment on what has changed since then some other time.
> Support showing log for the region (-L)

- lisp/magit-mode.el
- lisp/magit.el
If default-directory is used to check for an existing buffer, an
inappropriate magit buffer may be returned if its default-directory is
let-bound.  This is a similar problem as discussed in #2054 and #2060.
01cf031 (don’t bind default-directory to pass topdir to
magit-mode-setup, 2015-07-13) changed magit-status-internal to bind
magit-mode-setup--topdir instead of default-directory.  This fixes the
corner case with C-u C-u magit-status, but can still fail on third-party
code that let-binds default-directory.
One example of this is switching projectile projects with projectile-vc
as the action.  To switch to a new project, default-directory is
let-bound to the new project's root and then projectile-vc calls
magit-status-internal.  But if this is done from a status buffer that
doesn't …
> magit-mode-get-buffer: avoid default-directory test

- lisp/magit-process.el
- t/magit-tests.el
When git asks the user for a password, this patch first asks the auth-source library. If no password is found, prompt the user.
> Try to find the password before asking user

- lisp/magit-process.el
- lisp/magit-remote.el
Work around for #2309
---
I think this is basically ready to merge now. Note that `magit-credential-hook` is no longer a defcustom; the `--socket` argument needs to be customizable anyway, and this neatly avoids the `add/remove-hook` vs `defcustom` problem too.
> cache daemon hack

- lisp/magit.el
As a side effect, this fixes #2354.
> magit-git-command: drop --literal-pathspecs

- lisp/magit-bisect.el
- lisp/magit-diff.el
- lisp/magit-log.el
- lisp/magit-process.el
- lisp/magit-section.el
- lisp/magit.el
Face attributes set in overlays always have a higher priority than the
corresponding text properties.  Magit highlights the current section
with an overlay whose face sets the background color, as a result all
text in the current section would lose its background color.
We used to fake negative priorities for such text which has a background
color, by using an overlay to set the face where one would usually use a
text property.  So instead of giving the highlighting overlay a negative
priority, i.e. one lower than the 1 priority of text properties (because
that's impossible) we instead gave the text properties a higher priority
(by using overlay properties instead).  Conceptually that was equivalent
to giving the highlighting overlay a negative priority.
But we should not have done that …
> stop faking negative overlay property priorities

- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit.el
The only part that I expect might cause some protests, is no hasher appear anymore in the headers of status buffers. I hope that most users won't miss them once they have been told about `C-w`, but if that isn't the case, then I am willing to consider the addition of an option.
> Implement trivial parts of push-remote support

- lisp/magit-stash.el
Clarify how this command effects index and worktree.
This fixes #2397.
> Improve docstring of magit-stash-index

- Documentation/magit-popup.org
- Documentation/magit-popup.texi
- lisp/magit-popup.el
Add support for a new popup event type `:variable` to change Git
variables from a popup.  `magit-popup.el' isn't really up for the
challenge, so this is a bit of a hack.  It's intentional that the
documentation is sparse, as I don't want to encourage use outside
of Magit.  Magit is required to be able to use this new type, but
the byte-compiler won't complain if it is not available.
> popup: support new :variable event type

- lisp/magit-mode.el
On my machine (Ubuntu 14.04 running Emacs 24.5.1) pressing `<S-tab>` gets registered as `<S-iso-lefttab>` which gets translated to `<backtab>`, so keybinding for `magit-section-cycle-global` doesn't work.
This change fixes it by also binding `<backtab>`.
> add backtab binding for magit-section-cycle-global

- Documentation/RelNotes/2.4.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-popup.el
- lisp/magit-process.el
- lisp/magit-remote.el
- lisp/magit-section.el
- lisp/magit-sequence.el
- lisp/magit-stash.el
- lisp/magit.el
- t/magit-tests.el
Fully support the push-remote in addition to the upstream. They are both used to specify another branch related to the current branch, but serve different purposes. The push-remote is where the local branch is usually pushed to, while the upstream is where we want the changes to *eventually* end up.
The push-remote is configured using the variable `branch.<name>.pushRemote` or `remote.pushDefault`. The upstream is configured using `branch.<name>.remote` and `branch.<name>.merge`.
To some extend that was already supported previously - `Q` from the push popup pushed to the push remote, but for some odd reason it used `magit.pushRemote` instead of the two variables mentioned above. But the changes here go way beyond just using the correct variable.
The fetching, pulling, and pushing popups …
> Refactor branch handling

- lisp/magit-diff.el
- lisp/magit-log.el
- lisp/magit-section.el
and use it for `unpulled` and `unpushed` sections in the status buffer. That prevents these sections from being re-expanded when switching branches and when re-attaching `HEAD` (useful at the end of rebases).
> Generalize visibility cache

- Documentation/RelNotes/2.4.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-remote.el
```
Combine `magit-pull-popup' and `magit-fetch-popup' into one common
popup.  By default the old popups are still bound in `magit-mode-map'.
Add this to your init file to use the new popup:
(with-eval-after-load 'magit-remote
(define-key magit-mode-map "f" 'magit-pull-and-fetch-popup)
(define-key magit-mode-map "F" nil))
One advantage of the new popup is that it is once more possible to
press the same key twice to fetch.  However that binding now is "f f",
not "F F", and it fetches all remotes not just the current remote.
The new popup also lacks the commands for fetching from only a single
remote.  You can add them to the new popup by adding something like this
to your init file:
(with-eval-after-load 'magit-remote
(magit-define-popup-action 'magit-pull-and-fetch-popup ?U …
```
> magit-pull-or-fetch-popup: new popup

- Documentation/RelNotes/2.4.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- Makefile
- default.mk
- lisp/Makefile
- lisp/git-commit.el
- lisp/magit-apply.el
- lisp/magit-autorevert.el
- lisp/magit-core.el
- lisp/magit-mode.el
- lisp/magit-process.el
- lisp/magit-remote.el
- lisp/magit.el
```
Replace the old magit-specific auto-revert implementation with the
mode `magit-auto-revert-mode', a globalized variant of the built-in
`auto-revert-mode'.  By default Magit still explicitly triggers the
reverts after running git for side-effects.  Automatic reverts are
still enabled by default, and Magit is less verbose about it.  The
behavior can be tuned using `magit-auto-revert-' and `auto-revert-'
options.
The main benefit of this change is that this implementation caches
whether a file is tracked or not.  The old implementation determined
this on every revert cycle, which did not perform well when there
were many open buffers and/or many tracked files.
```
> revert buffers using a globalized variant of auto-revert-mode

- lisp/magit-autorevert.el
* Make sure magit-revert-buffers is defined when magit-autoloads.el is
loaded because it will be used with :init-value.
* Avoid a recursive loading error that results from the
magit-auto-revert-mode command being autoloaded.
> autorevert: fix autoload-related errors

- Documentation/RelNotes/2.4.2.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-autorevert.el
```
Add new option `auto-revert-buffer-list-filter' and redefine
`auto-revert-buffers' from `autorevert.el' to use it.  Add new
predicates `magit-auto-revert-buffer-p' and the more restrictive
`magit-auto-revert-buffer-p', which are both intended to be used as
potential value of the option.
For now the option defaults to `nil', but that might change in a future
release.  When Magit explicitly calls `auto-revert-buffers' (as opposed
to when that is called due to a file notification event or by a timer),
and `auto-revert-buffer-list-filter' is `nil', then it is let-bound to
`magit-auto-revert-repository-buffer-p'.
Users who use Tramp and experience delays, should consider setting
the option to `magit-auto-revert-repository-buffer-p'.
```
> Try to limit reverts to buffers for current repository

- lisp/magit-apply.el
- lisp/magit-bisect.el
- lisp/magit-process.el
- lisp/magit-stash.el
Re: https://github.com/magit/magit/issues/2454#issuecomment-171090747
We can send input to synchronous subprocesses with `call-process-region`, but there is no file-handler equivalent (like `process-file` for `call-process`), so this may have problems when using magit over tramp.
> Don't busy wait for subprocesses

- Documentation/RelNotes/2.4.2.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-log.el
```
Before `git log' is called, `++order=TYPE' is converted to
`--TYPE-order', one of `--topo-order', `--date-order', and
`--author-date-order'.  We do that instead of adding the
individual arguments to the popup because they are mutually
exclusive.
```
> log: add ++order pseudo option

- Documentation/RelNotes/2.5.1.txt
- lisp/magit-diff.el
```
The old implementation was a hack, which got extended when I got myself
into a situation where the current version failed (seriously, is nobody
else using submodules?).  This time it was "(not checked out)" which was
not handled.  Upon inspecting `show_submodule_summary' in `submodules.c'
it turned out that "(revision walker failed)" also wasn't handled, and
why there sometimes is a trailing colon and sometimes not (there's a
colon when commits follow, so the colon cases should be handled
separately even though that leads to a bit of duplication).
At present these are the lines we have to look for.
Submodule <module> contains untracked content
Submodule <module> contains modified content
Submodule <module> a...b:
Submodule <module> a...b (rewind):
Submodule <module> a...b (submodule …
```
> magit-diff-wash-submodule: rewrite from scratch

- Documentation/RelNotes/2.6.0.txt
- lisp/magit-section.el
Replace cl-mapcan, which uses nconc, with -mapcat, which uses append, to
avoid modifying section children.
Fixes #2579.
> magit-section-cycle-diffs: fix hanging when hiding

- lisp/magit.el
This patch aims to streamline the placement of the trailing `\n` in the "Untracked Files" section with that of all the other sections.
Without this patch, the trailing newline for this section is inserted outside of it. As a consequence, it's not hidden when that section is closed, and a single empty lines between the section headers remains visible.
> move trailing newline into `Untracked Files` section

- lisp/magit.el
Trivial addition to support cases where users have `magit-file-popup` bound to a key and may invoke it before e.g. `magit-status`.
> magit-file-popup: autoload it

- lisp/magit-git.el
On OS X `make-temp-name` triggers a 'bad file descriptor' error when
passed a non-absolute file path. Moving `magit-git-dir` inside
`make-temp-name` ensures that an absolute file path is available.
This fixes #2633, where the above is also discussed.
> Pass absolute file name to `make-temp-name`

- lisp/magit-mode.el
This possibly a bug reported in the chatroom:
> Here is what I got when I press `c c` in a magit buffer:
`*ERROR*: Wrong type argument: listp, inhibit-same-window error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'. Please supply the message using either -m or -F option.`
I made this fix because I think there is a missing layer of nesting around the alist, but committing is working for me either way (Emacs 24.5), so I'm not really sure if this fixes anything (hence I didn't commit this to `master` directly).
> magit-display-buffer-traditional: fix alist syntax

- Documentation/RelNotes/2.7.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-popup.el
- lisp/magit-remote.el
- lisp/magit.el
Replaces  #2596.
I am not going to merge this before releasing v2.6 because I realized that we should also use this separate popup to allow customizing variables for branches that are not currently checked out. 
Currently one has to use a prefix argument to do that but that's not nice because one cannot see the value before changing and cycling a value also isn't much less fun if you have to use the prefix on every turn.
But how exactly we should use this popup to provide a better interface for that I don't know yet.
> magit-branch-config-popup: new popup 

- Documentation/RelNotes/2.7.0.txt
- lisp/magit-process.el
- lisp/magit-remote.el
should fix #2639.
```
This allows intercepting password prompts, and is also nicer if the
clone happens to take a long time.
```
---
I'm having some trouble with the error reporting for when the clone happens to fail. See FIXME in code.
> magit-clone: run asynchronously

- Documentation/RelNotes/2.7.1.txt
- lisp/magit-process.el
```
Ultimately all sections are inserted using `magit-insert-section',
which binds a few variables dynamically, to pass information to nested
invocations, among other things so that those invocations know what to
use as the parent section of the section that they are inserting.
Normally I avoid the use of dynamic bindings to pass around information,
but in this case it seems appropriate, because the "nested"
`magit-insert-section' invocations often cannot be found lexically
inside the outer invocation, and the cost of passing these values around
as arguments would therefore be very high; a great many functions (which
shouldn't have to concern themselves with this particular implementation
detail) would need additional arguments.
Also the current approach works quite well, because normally …
```
> Don't use section bindings from other buffers in process buffer

- lisp/magit.el
When `magit-show-refs-popup` is called in a detached HEAD throws an error because `(magit-get-current-branch) => nil`
> magit-branch-description: Fix for detached head

- lisp/magit.el
Adjust downstream processing of magit-repository-directories to let an
element of magit-repository-directories be a directory name (that is,
end in a slash) rather than a directory file name.  This prevents an
alist with empty strings for all keys from being passed to
magit-list-repos-uniquify, in which case the function believes that all
repos should be uniquified.
> allow magit-repository-directories to be directory names

- Documentation/RelNotes/2.7.1.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit.el
An element can now be a cons-cell whose cdr is the depth.  For elements
that are strings the value of `magit-repository-directories` is still
used.
---
Suddenly I can no longer export the manuals and have yet to figure out what changed. @kyleam could you please regenerate the manual and amend to this commit for me.
> allow magit-repository-directories to specify depth per element

- lisp/magit.el
Restore code that is necessary for multi-key bindings (currently M-r and
M-p).  This code was removed in 75abae8 (magit-branch-popup-setup:
remove unnecessary function, 2016-05-12).
Fixes #2695.
> magit-branch-{,config-}popup-setup: restore M-r/M-p

- lisp/magit-submodule.el
This fixes the following use case:
1. `git clone` some repo inside of your other repo, not with Magit (e.g. in shell).
2. Open Magit Status buffer.
3. Try to stage that new cloned directory using `s`.
If no Magit's submodule related functionality was used after the Emacs startup, the following error will occur:
```
Debugger entered--Lisp error: (void-function magit-submodule-read-name)
magit-submodule-read-name("layers/my-web-dev/local/ede-php-autoload/")
magit-stage-untracked(nil)
magit-stage(nil)
call-interactively(magit-stage nil nil)
command-execute(magit-stage)
```
> Make magit-submodule-read-name autoloadable

- lisp/magit.el
Until I looked at the manual, I didn't realize that magit supports subtree commands.  Mostly because I don't check the manual, figuring the dispatch pop-up will tell me what I want to know.  This adds subtrees to the dispatcher.
> Include subtrees in the dispatch pop-up

- Documentation/RelNotes/2.7.1.txt
- lisp/magit-ediff.el
- lisp/magit.el
```
When using ediff to stage, the working tree file is visited by Emacs in
the normal way, so Emacs applies normal encoding detection on it.  We
must apply the same encoding the output of `git cat-file' (used by
magit-find-file-{,index}-noselect) so that ediff can apply diffs
sensibly.
When writing back the changes back to git (via magit-update-index), we
have to use the same encoding to write as the one used to read, or else
we may ending changing the file recorded in git in a completely
unintended way.
```
fixes #2701.
We might want make encoding match across buffer for a few other ediff functions, `magit-ediff-show-working-tree` and `magit-ediff-show-stash` perhaps? To let the user choose different encodings, I think the best way is to set the `revert-buffer-function` so that <kbd>C-x …
> magit-ediff-stage: use same encoding for all texts

- lisp/magit-blame.el
Currently, magit uses black text for both light and dark themes. For
dark themes, this means there's very little contrast and commit messages
are hard to read.
Instead, use a constrasting color for dark themes.
Before:
After:
> Use higher contrast for magit-blame with dark themes.

- lisp/magit-diff.el
This allows `magit-show-commit` work with buffers opened with `magit-diff-visit-file`
> magit-show-commit: use magit-buffer-refname

- lisp/magit-blame.el
`magit-blame-popup` has opposite help strings for =M and =C options.
> Errata for blame popup

- lisp/git-rebase.el
```
The git-rebase-todo buffer is frequently in a modified state, but there
is no need to save it before showing a commit.  It will be taken care of
by with-editor-return when the user exits through with-editor-finish.
The unsaved buffer should almost always be the git-rebase-todo because
the initial 'git rebase' call will fail if there are unstaged changes.
The user could unwisely go and modify some other tracked buffers after
starting a rebase, and this could put things into a bad state [1], but
this is unrelated to whether the user happened to call a command to show
a commit.
Closes #2770.
[1] And, when the user has done this, I don't think there is really any
good action to take to fix the situation.  It's bad whether or not
the buffer is saved.  The user should just never start an …
```
> git-rebase: disable save check when showing commits

- lisp/magit-commit.el
- lisp/magit-git.el
- lisp/magit-process.el
- lisp/magit.el
Fixes #2794.
https://github.com/magit/magit/issues/2794#issuecomment-252183157:
> If it's around every call, why not just move it inside?
The need to do this binding is git specific, so the decision can't be made by `with-editor`.
> `magit-with-editor` is probably the best we can do.
Yes.
> let-bind `shell-file-name' around with-editor calls

- lisp/magit-git.el
- lisp/magit-process.el
All git commands which print file names and similar encoding in utf-8 on
Windows.  The encoding of commit messages is controlled by
i18n.logOutputEncoding, but it's easier to set that to UTF-8 than try to
distinguish between commands that respect and those that don't.
magit-log-output-coding-system should probably be obsoleted/removed.
> Properly decode git utf-8 output on Windows

- lisp/magit-git.el
When we're not actually inside a git repo, `magit-git-dir` returns nil. `file-in-directory-p` takes offense to this.
> Fix magit-inside-gitdir-p

- lisp/magit-mode.el
There's no need to turn it off simply if `linum-mode` is bound (which is always, as `linum-mode` is autoloaded).
> Only turn (n)linum-mode off in global-(n)linum-mode

- lisp/magit-diff.el
I noticed that Emacs would sometimes thrash the disk very hard when I saved a file to disk.  By running `pkill -SIGUSR2 -f emacs` I saw that it was happening in magit's hunk-refining code.  I followed the calls and tracked it down to `smerge-refine-chopup-region`.  The problem seems to be that it writes many small files, and when Emacs is running in interactive mode, `write-region` calls `fsync`.  This results in many calls to `fsync`, which results in much disk thrashing and an unresponsive Emacs.
When `magit-diff-refine-hunk` is set to `all`, and the status buffer shows many changed hunks, this is a big problem, causing Emacs to thrash the disk for many seconds at a time, even when the status buffer is buried.
However, there seems to be a simple fix for this problem: Set …
> Inhibit fsync when refining hunks

- lisp/magit-process.el
When magit-process.el is loaded in an environment where Git can’t be
executed (e.g. in a container or when Git isn’t installed), loading
fails.  Work around this by catching ‘file-error’ and turning it into a
warning.
> Don’t raise errors when initializing ‘magit-need-cygwin-noglob’

- lisp/magit-log.el
```
magit-log-stash-re matches the space after the hash as the author to fit
in with the other regexps used by magit-bind-match-strings in
magit-log-wash-rev.  This, however, results in a non-nil author argument
to magit-format-log-margin.  Because magit-stashes-mode derives from
magit-reflog-mode and uses its date-only margin specifications, a
non-nil author argument pushes the date outside of the margin width in
magit-stashes-mode.
Make magit-log-wash-rev set author to nil when washing stash lines so
that magit-format-log-margin receives the expected argument of nil for
author.
See #2846.
```
> magit-log-wash-rev: set author to nil for stash lines

- lisp/magit-log.el
- lisp/magit.el
```
This adds support for Git 2.11's additional status letters for the %G?
specifier.
The magit-signature-bad face was given a bold weight to help distinguish
it from the new magit-signature-error face.
```
This covers the new status codes implemented [in upcoming Git 2.11](https://github.com/git/git/commit/56d268bafff7538f82c01d3c9c07bdc54b2993b1).
I'm not sure on the colours, but they seem to look alright.
> Add gpg status letters X, Y, R, and E

- lisp/git-commit.el
This ensures file and directory local variables are setup in the
standard way.
See #2848. This still leaves `git-commit-fill-column` overriding `fill-column`. Actually, I don't quite see why `git-commit-fill-column` exists at all...
> git-commit-setup: use normal-mode

- lisp/git-rebase.el
reverse the lines defining key-bindings for git-rebase-kill-line.
this is a pragmatic change to display 'k' rather than 'C-k' for git-rebase-kill-line in the help-text at interactive rebasings.
> display 'k' rather than 'C-k' for rebase-kill-line

- Makefile
- lisp/Makefile
- lisp/magit-section.el
`make clean` should do `rm *.elc` instead of `rm $(ELCS)` to ensure removing all
the .elc files, including those obsolete residue ones. Obsolete residue .elc
files are usually not included in `$(ELCS)` because `$(ELCS)` is computed from
`$(ELS)` by the following substitution rule:
`ELCS = $(ELS:.el=.elc)`
while the obsolete source files are not in `$(ELS)`.
A real life example is the residue file `lisp/with-editor.elc`. Apparently,
`with-editor.el` used to be part of Magit, but was moved out into a dependency
package. The old "make clean" wasn't able to delete the file `with-editor.elc`
for the reason explained above. This caused the `make` command always used the residue file `with-editor.elc` instead of the new one in the `with-editor`
package.
> "make clean" should do "rm *.elc"

- lisp/git-rebase.el
Hi guys!
This is another detail suggestion concerning the documentation of keys at rebase.
Recent: SPC is missing.
New:
1. SPC occurs in the "Commands" list.
2. SPC gets the text of (the recent) RET.
3. RET gets the hint that point moves away.
Best regards!
Marco
> note SPC at rebase. distinguish SPC, RET

- lisp/git-commit.el
The docstring refers to `overlong-summary-line`, whereas the symbol used in the file is called `overlong-first-line`.
Although the latter is consistent with `non-empty-second-line` in its use of line numbers, I think "summary line" indeed makes more sense.
> doc fix: correct git commit style convention name

- Documentation/RelNotes/2.9.0.txt
- ISSUE_TEMPLATE
- lisp/magit-utils.el
Refer: https://github.com/magit/magit/issues/2856#issuecomment-261773690
> It might be better to show the actual command, possibly prefixed with instructions.
I did that. Not sure if showing the command is a good idea, it's a bit long.
Fixes #2856.
> magit-emacs-Q-command: new command, for debugging

- Documentation/RelNotes/2.9.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/Makefile
- lisp/magit-core.el
- lisp/magit-log.el
- lisp/magit-margin.el
- lisp/magit-mode.el
- lisp/magit-stash.el
- lisp/magit-utils.el
- lisp/magit.el
This is the second part. The first part happened directly on `master`, mostly in 186c3d6ccbca78386cb0faa69164b3396bb38ae6 and in response to #2792.
* Generalize margin support as described in 3881bbb2540e07c6f75ef3c675b38bca023f2649.
* Add commands to toggle margin details and cycle the margin style.
This changes the form of margin options again, but better do that now after five days and before the release than later when more than a handful of users have already adapted.
> Generalize margin and add commands to change its appearance

- Documentation/RelNotes/2.9.0.txt
- lisp/magit-section.el
Set `magit-section-highlight-overlays' to nil in addition to mapping
delete-overlay over it to remove all references to those overlays.
Otherwise `magit-section-highlight-overlays' grows unbounded, since `delete-overlay' only causes overlays to be unlinked form the buffer, they don't actually cease to exist. When we remove all references they should (hopefully) be garbage collected.
> Discard highlight-overlays

- lisp/magit-utils.el
This matches the absolute paths for library directories.
> Use absolute path for magit-emacs-Q-command load file

- Documentation/RelNotes/2.9.1.txt
- lisp/magit-mode.el
Usefull for multiframe configrations, overriding `magit-display-buffer-function` does not work as expected.
> Raise not just window but frame also

- lisp/magit-log.el
```
The comment added in d430d856 (magit-log-wash-rev: work around `git
reflog show' bug, 2016-12-01) states that the partial trailing line
"has no basis in the data stored in the file".  However, as far as I
can tell, this partial line occurs if some reflog entries have been
expired (e.g., by 'git gc').  The reported hash on this partial line
seems to always correspond to the "old hash" field of the oldest
reflog entry.  That is, this hash is the first field of the first
entry in the corresponding .git/logs/refs/ file.
Update the comment to reflect this.
See also 81a6241e (magit-log-reflog-re: Allow for partial line,
2015-04-11).
```
> magit-log-wash-rev: correct reflog comment

- Documentation/RelNotes/2.9.1.txt
- lisp/git-commit.el
- lisp/magit-blame.el
- lisp/magit-ediff.el
- lisp/magit-mode.el
- lisp/magit-submodule.el
- lisp/magit-utils.el
- lisp/magit.el
magit-hook-custom-get: new function used to initialize hook options
Fixes #2902.
I did some rudimentary testing using 
```lisp
;;; Preparations
;; Don't (package-initialize)
(add-to-list 'load-path "~/.emacs.d/lib/dash")
(add-to-list 'load-path "~/.emacs.d/lib/with-editor")
(add-to-list 'load-path "~/.emacs.d/lib/magit/lisp")
;;; Variant 1: no customizations
;;; Variant 2: using Custom
;; (custom-set-variables
;;  '(git-commit-setup-hook
;;    (quote
;;     (git-commit-save-message git-commit-setup-changelog-support git-commit-turn-on-auto-fill git-commit-turn-on-flyspell git-commit-propertize-diff with-editor-usage-message)))
;;  '(package-selected-packages (quote (magit))))
;;; Variant 3: using add-hook
;; (add-hook 'git-commit-setup-hook 'git-commit-turn-on-flyspell)
;;; Test
(require …
```
> Properly initialize hook options

- lisp/magit-refs.el
- lisp/magit-status.el
Just noticed these while checking the git calls for #2909. This shaves off another call to `git config` during refresh, doesn't make a noticeable change in speed.
Before: `Refreshing magit...done (0.450s, cached 46/73)`
After: `Refreshing magit...done (0.449s, cached 48/74)`
> Use magit-get instead of magit-git-string

- lisp/magit-extras.el
Do you mind to make `ido-enter-magit-status` available right away?
> Autoload ido-enter-magit-status

- lisp/magit-git.el
Hi!
This solves a bug I have with `magit-ediff-dwim` in a diff buffer generated from the "Unpulled from" section of the status buffer. To reproduce:
```bash
git init origin; cd origin
echo "hello" > README; git add README; git commit -m "Add README"
git clone . ../local
echo "Hello world!" > README; git add README; git commit -m "Fix README"
cd ../local
git fetch
emacs
```
In Emacs:
- <kbd>M-x</kbd> magit-status
- On "Unpulled from origin/master (1)": <kbd>d d</kbd>
- On "modified  README": <kbd>e</kbd>
`magit-ediff-dwim` fails, saying `magit-split-range: Args out of range: #<buffer *magit-diff: local>, 0, 2`.
The problem seems to be that `(magit-split-range "..@{upstream}")` fails:
Debugger entered--Lisp error: (args-out-of-range #<buffer *scratch*> 0 2)
match-string(2)
(string-equal …
> magit-split-range: fix handling of "..@{upstream}"

- lisp/git-commit.el
Hello, I hope the commit message is clear what I mean: I work on a
project that has `.dir-locals.el` file with unsafe variables, so every
time I make a commit, I get a standard message about local variables
that "may not be safe", etc.
This happens because `normal-mode` sets `enable-local-variables` to `t`
when it is called without arguments.
I called `normal-mode` with `t` argument since any non-nil value suits,
although you can guess from the docstring that `find-file` should
probably be a string, so using `t` is like violating the documented
thing; is that OK?
> Fix git-commit to honor 'enable-local-variables'

- Documentation/RelNotes/2.10.1.txt
- lisp/magit-commit.el
- lisp/magit-git.el
```
If a repository is created using `git init --separate-git-dir', then
that does not set `core.worktree' (unlike what `git submodule' does).
When committing inside such a repository `magit-commit-diff' is run
inside the gitdir, and there is no way to prevent that.  Luckily `git
diff' also works inside the gitdir, but because many other commands
don't, we always run everything in the working tree.
This is fairly deeply ingrained, so we have to add a kludge to
`magit-toplevel', that causes it to return the gitdir instead,
and that is triggered by dynamically binding the new variable
`magit-toplevel--force-fallback-to-gitdir' to a non-nil value.
And `magit-commit-diff' now does so to fix #2955.
```
Fixes #2955.
> While committing, diff from inside gitdir if necessary

- Documentation/RelNotes/2.10.2.txt
- lisp/magit-git.el
- lisp/magit-process.el
I'm not sure if this is the direction we should go, but it's the best
I've come up with so far.  If we do want to go with someting along
these lines, I should think more carefully about the last paragraph of
the commit message.
#2955
-----------------
```
magit-toplevel needs to determine the working tree from inside .git/
when a buffer is visiting COMMIT_EDITMSG or various other files.  To
do this, it uses the following logic:
1) file is in .git/modules/<module>/: set working tree to the output
of "git rev-parse --show-toplevel"
2) file is in .git/worktrees/<wtree>/: set working tree to the path
in .git/worktrees/<wtree>/gitdir, minus the trailing "/.git"
3) file is in .git: set working tree to the parent directory
This, however, fails when a repository was set up by passing …
```
> Record the working tree for separated git directories

- Documentation/RelNotes/2.10.2.txt
- lisp/git-rebase.el
If you do a rebase and drop all the commits in the file, git will do nothing, because the file is considered empty (everything is commented). If you really do want to remove all the commits, you have to insert a `noop` action which prevents the file from being empty. It has no other purpose.
This commit lets the user add such a `noop` action. Currently, you have to switch to a different mode (e.g. text-mode), disable the read only mode, add `noop` manually and switch back.
> Add new function `git-rebase-noop` to add a noop action at point

- Documentation/RelNotes/2.10.3.txt
- lisp/magit-diff.el
- lisp/magit-extras.el
Emacs is not good at opening every possible kind of file. For those rare cases, it's always good to be able to launch an external command.
> Add `&' on a file to open it with dired-do-async-shell-command

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-diff.el
Update documentation with new whitespace highlighting variable names introduced in ea668709.
> Doc fix: magit-diff whitespace highlighting variable names

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-remote.el
Added "that" between "provided" and "the name of".
Removed the duplicate words "the name of".
The corrections were made in the
magit-remote-add-set-remote.pushDefault
variables docstring and in it's magit.org documentation.
> magit-remote-add-set-remote.pushDefault: doc correction

- Documentation/RelNotes/2.10.4.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-remote.el
- lisp/magit-utils.el
This PR makes the following changes:
* Allow the sorting key of `magit-list-refs` and friends to be
customized.
* Prevent the default Emacs completion from alphabetically sorting
the collection items before displaying them to the user.  There's
still a remaining issue with the `crm` completion functions and
global `helm-mode` or global `ivy-mode` that this PR doesn't
address.
Please see the commit messages.
Re: #2872, #2925
> Order of ref completions

- .travis.yml
I have some Emacs binaries for Travis at https://github.com/npostavs/emacs-travis/releases
They can run in the non-sudo environment, but unfortunately, magit's tramp test requires sudo to run. Possibly we could change it to use ssh instead (I've checked that sshd is installed on Travis), though I'm not sure if it's worth bothering with that.
> Test with more Emacs versions

- Documentation/magit.org
- lisp/magit-git.el
- lisp/magit.el
From recent stackexchange questions, I think our `magit-version` command is not sufficiently foolproof for a troubleshooting tool.
http://emacs.stackexchange.com/questions/31913/how-to-direct-m-m-xs-output-to-the-current-buffer-rather-than-to-the-ec
http://emacs.stackexchange.com/questions/31868/magit-version-post-installation-does-not-look-as-in-the-manual
> Improvements to magit-version

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-bisect.el
- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-log.el
Please see commit messages.
Fixes #3028.
> log: use NUL to delimit refs

- Documentation/magit-popup.org
- Documentation/magit.org
- lisp/magit-utils.el
It's nice to be able to collapse the text in section that comes before its subsections when working on the org source. But we don't want these dummy sections to appear in the exported files. `ox-extra` implements support for that, but unfortunately it appears to have a bug (maybe a regression when used with org v9), sections now contain the subsection menu twice.
I have contacted the author, @aecay, by email (because he isn't very active on github and might not see this otherwise).
> In the manual, add dummy subsection, wrapping initial section content

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-git.el
Fix commit messages which are over written with signature, when
using `log.signatureEnabled=true`. #3061
> fix show signature

- lisp/magit-utils.el
```
org-extra--merge-sections was added to ox-extra.el in Org's
fef346798 (ox-extra: Merge sections from ignored headlines,
2017-05-03).
Re: #2914
```
@tarsius I'm opening this as a PR so that you can merge it whenever
you've updated your Org installation.
> Remove org-export-ignore-headlines advice

- lisp/git-commit.el
This will allow users to register `git-commit-mode` with `auto-mode-alist` without having to enable `global-git-commit-mode` and thus eagerly load the whole `git-commit.el` package.
The motivation for this change was [this Q&A](https://emacs.stackexchange.com/q/32676/15748). If the proposed addition of an autoload cookie is not acceptable/desirable, I would be grateful for any suggestions addressing the points in the linked question.
> git-commit-filename-regexp: autoload

- Documentation/RelNotes/2.11.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-diff.el
- lisp/magit-log.el
```
All calls to magit-show-commit take the file restriction from
magit-diff-arguments.  But when a call is made from a log buffer, the
user is viewing the revision in the context of the log, so the log's
file restriction is more relevant than the diff's [*].
Adjust magit-show-commit calls to respect the log's file restriction
if the current buffer is a log buffer.  Leave calls to
magit-show-commit in git-rebase.el and magit-blame.el unchanged
because these aren't designed to be executed from a log buffer.
Closes #3056
[*] This patch assumes that all users would prefer the log's file
restriction over the diff's in this situation, but of course we
can add an option to revert to the previous behavior if this turns
out not to be the case.
```
Re: #3056
> magit-show-commit: when in a log buffer, use log's file restriction

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-remote.el
```
Extract the directory name by taking the tail of the url up to the
first slash or colon, not the first slash or period.
This makes magit-clone's default directory name match the behavior of
"git clone <url>" in two places where it did not:
1. https://[...]/foo.bar.git => "foo.bar" (instead of "bar")
2. host.xz:foo/.git => "foo" (instead of "git")
Fixes #3079.
```
> magit-clone: improve suggested directory name

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-subtree.el
* lisp/magit-subtree.el (magit-subtree-add): Complete repo and branch
(magit-subtree-pull): Complete repo and branch
(magit-subtree-push): Complete repo
This could probably be taken farther, but this was as far as I was comfortable with.
> Use completion in magit-subtree.el

- lisp/magit-utils.el
Until now, we did not bother adding the default choice to the list of
all choices, because we assumed that doing so was not necessary.
But it turned out that while it is possible to use such a default by
simply confirming it, `completing-read` does not actually added to the
list of all choices.  It therefore won't be shown when the user uses
TAB to list the choices and manually typing the default and then
exiting with RET also won't work.
Additionally `ivy-completing-read` was recently changed to completely
ignore a default that isn't a member of the choices, making a fix more
pressing.
This commit simply prepends the default to the list of choices, if it
is not a `member` yet.  Doing this is much simpler than adjusting each
and every caller of `magit-completing-read`, but it may in some …
> magit-completing-read: add default to choices if necessary

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-log.el
Previously, the line numbers passed to `git log`'s `-L` arg were calculated by subtracting 1 from
`line-number-at-pos` for `region-beginning` and `region-end`, which was incorrect in some cases.
e.g. calling `mark-whole-buffer` in a file with a single line with a trailing newline would call
`git log -L0,1:file`, instead of the expected `git log -L1,1:file`.
Additionally, if the active region does not include a trailing newline, the end of the range passed
to `-L` would also be off by 1. (e.g. in a 1-line file with no trailing newline, it would call `git
log -L0,0:file`)
This fix changes `magit-log-buffer-file` to calculate `-L` as a range starting at `the line number
at the start of the region`, and ending at `the line number at start + total lines in the region -
1`.
This appears to fix …
> magit-log-buffer-file: fix `-L` arg when region is active

- lisp/magit-git.el
```
magit-ref-ambiguous-p uses magit-ref-fullname to check if a ref is
ambiguous, but this results in some non-ambiguous names being
considered ambiguous because "git rev-parse --symbolic-full-name"
doesn't handle names like master~1.
We had the same problem before the introduction of
magit-ref-ambiguous-p (7026b9bd) because we used magit-ref-fullname
directly to check whether a ref was ambiguous.  However, we only used
this in a couple of places, and it looks like the only problematic
case (i.e. where we passed a ref with a ^ or ~ suffix) was in
magit-get-shortname (which led to an unnecessary "tags/" prefix for
unambiguous tags).
As of 622c9941 (Merge branch 'km/show-ambig' [#3101], 2017-06-10), we
rely on the magit-ref-fullname check (through magit-ref-ambiguous-p)
more heavily, so the …
```
> magit-ref-fullname: support revision suffixes

- lisp/magit-git.el
Please see the commit messages.
#3106
> magit-rev-name: anchor the ref pattern by default

- lisp/git-rebase.el
* This causes it to reject lines like "# pick ..." generated by
magit-rebase when using git-rebase-kill-line
> git-rebase-line regexp did not support spaces before pick commands

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-status.el
This allows user input, whether read interactively or from `magit-repository-directories`, involving symlinked files to be compared to the result of `magit-toplevel` with `find-file-visit-truename` enabled. Otherwise, `magit-status` in particular fails to show the status corresponding to a symlinked directory in `magit-repository-directories`, and instead asks the user to create a new repository.
My personal need for this arises from configuring `magit-repository-directories` to list a single directory containing symlinks to all other repositories in my filesystem. This saves me from having to maintain the list in my `user-init-file`. I only noticed the `magit-status` issue after recently enabling `find-file-visit-truename`. Though I can't imagine how the introduction of `file-equal-p` …
> magit-{init,status}: compare toplevels by truename

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-mode.el
- lisp/magit-process.el
Continued from #3094.
This initial revision is just the simplest thing possible: extend the refresh cache around `magit-run-git`. We might get in trouble if the git command we run changes something we cache, I'm not sure if that can happen though? The main savings seems to be the `rev-parse` calls, so we could filter the cache to keep just those if it's a problem.
Here's the diff of git calls for a single `magit-stage`.
```diff
--- count-master.txt	2017-06-01 00:10:11.951496805 -0400
+++ count-cache2.txt	2017-06-01 00:11:07.457862768 -0400
@@ -22,27 +22,13 @@
git show --no-patch --format=%s master^{commit} --
git rev-parse --verify master
git config --list -z
-git rev-parse --show-cdup
-git rev-parse --show-toplevel
git show --no-patch --format=%h %s current^{commit} --
git symbolic-ref …
```
> [WIP] Use cache around magit-run-git calls

- Documentation/RelNotes/2.11.0.txt
- lisp/magit-commit.el
```
As mentioned in git-reset's manpage, ORIG_HEAD can be useful for
undoing a commit and reusing its message (though there are of course
other ways to do this).  Define a reader for the --reuse-message
option that offers ORIG_HEAD as the default value when it exists.
Also, prompt with all ref names.  If these aren't useful for the given
situation, the user can ignore them and enter an arbitrary value.
```
Closes #3110.
------------------------------------------------------------------------
I went back and forth on whether it's useful to include all ref names,
so I also have another version that uses `magit-read-string-ns`.
Thoughts?
> magit-commit-popup: add custom reader for --reuse-message

- Documentation/magit-popup.org
- Documentation/magit-popup.texi
The document says that the package will be deprecated eventually, what should I use instead? Does current version of Magit use `magit-popup`?
> Fix typos in Magit popup manual

- lisp/magit-extras.el
```
Using call-process fails when the PATH doesn't contain the git-gui
executable (e.g., when Git for Windows was installed with only the
cmd/ directory on PATH).
```
I'm not entirely sure if the use of `call-process` vs `process-file` is just an oversight, or it was meant to avoid opening a gui on the remote (when using tramp). In the latter case we might need to add a `magit-call-process` function.
> magit-run-git{k,-gui*}: Use magit-process-file

- Documentation/magit-popup.org
- Documentation/magit.org
This is the default, but a non-nil value changes the way whitespace in
literal blocks is handled during export, so make the assumption
explicit by a file-local variable.
> magit{,-popup}.org: make sure org-src-preserve-indentation is nil

- Documentation/magit.org
- Documentation/magit.texi
Looks like it should be `C-c, M-s`, not `C-s, M-s`.
> Fix typo in key chord of git-commit-save-message

- lisp/magit-popup.el
Binding these variables is needed to ensure behavior that was implicitly assumed. Fixes #3173.
> magit-popup: locally set help-window-select and display-buffer-overriding-action

- lisp/magit-process.el
> magit-run-git: Delete cache after running "init" or "clone"

- Documentation/RelNotes/2.11.1.txt
- lisp/magit-section.el
Normally `C-S-n`, sets the mark and then moves down one line, resulting in one line being selected by the region. The same thing happens in Magit (because we don't handle this specifically yet), but because Magit's "selection mechanism" is only *based* on the region, but actually spans a wider area, this keeps surprising users.
The selection begins at the beginning of the line on which the beginning of the region is and ends at the end of the line on which the end of the region is. The effect of this is that a single `C-S-n` selects *two* lines. The region is still the same, but the region is not visualized and so it looks like `C-S-n` works differently in Magit buffers.
For multi-section selections I think we should stick to that. Such a selection always contains at least two sections. …
> Make Shift-selection less surprising

- Documentation/RelNotes/2.11.1.txt
- lisp/magit-refs.el
* Like for diff and log buffers
* Useful for #2872.
* Despite #2894, and unlike for diff and log, there *probably* won't be a show-new and a refresh variant.
* Maybe rename to `magit-list-references`.
The current implementation on this branch was created before I realized that the arguments are not being remembered (and how much work it would be to do that), and is therefore not suitable for merge.
> Remember arguments used in refs buffer and allow updating  them without prefix arg

- Documentation/RelNotes/2.11.1.txt
- lisp/magit-diff.el
- lisp/magit-log.el
Highlighting keywords in brackets is a useful feature in case the convention in the project is to use such brackets to mark references to issues and PRs (for example on github).
However, in our project such brackets are often used for other purposes and I dislike the highlighting, so I would like to make it optional. As far as I know, customizing the magit-keyword face does not work, because it is used in two different places where the surrounding characters have differing faces so I wouldn't know how to set the magit-keyword face such that it resolves to face A (in magit-log) and face B (in magit-diff). If you have an idea how to do this the patch here wouldn't be required and I would appreciate hearing it.
I would have preferred to add only one defcustom, but I didn't find a good place …
> Make highlighting keywords in brackets optional

- Documentation/RelNotes/2.12.0.txt
- lisp/magit-log.el
- lisp/magit-refs.el
And other cleanup. Keywords are now properly highlighted.
Closes #3179.
> Use --format with \0 separated fields in refs buffer

- lisp/magit-diff.el
- lisp/magit-log.el
- lisp/magit-popup.el
- lisp/magit-refs.el
- lisp/magit-section.el
- lisp/magit-stash.el
- lisp/magit-utils.el
- lisp/magit.el
A space is not a robust alignment; the left fringe may not be the same pixel
width as a space, and there may not even be a fringe present (e.g., terminal
Emacs).
In my current installation, the fringe width is one pixel less than the width of a space, and once you see that one pixel offset you just can't ignore it.
> Align header-line contents with the text area

- lisp/magit.el
If `magit-git-executable` is an absolute path, the `unless` form will evaluate to nil, which crashes `insert`.
Wrap all the inserted forms with `concat` first, which handles nil more intuitively.
> Avoid crash in magit-debug-git-executable

- Documentation/magit.org
- Documentation/magit.texi
- Update some typos, such as "to" to "too"
- Update grammar where appropriate, such as commas and verb conjugation
- Update to name spelling, such as Git and TRAMP
> Fix documentation typos and grammar

- lisp/magit-refs.el
```
9cac1f53 (magit-insert-{local,remote}-branches: use NUL separated
fields, 2017-10-11) breaks magit-show-refs because "git branch" does
not support the --format option in Git versions earlier than 2.13.
[WIP] We can *almost* use for-each-ref as a drop-in replacement.  The
only discrepancy I've noticed is that the local refs do not include an
entry for a detached head.  At first glance, I don't see an issue with
dropping this because the buffer is about listing refs.  Thoughts?
```
Fixes #3203.
> magit-insert-{local,remote}-branches: use for-each-ref

- lisp/magit-branch.el
Using the non-local version was just a copy-pasta mistake, right?
> magit-branch-reset: use magit-local-branch-at-point

- Documentation/magit.org
- Documentation/magit.texi
I noticed one spelling issue in the manual, so I ran ispell and fixed the issues it spotted.
> Minor spelling fixes in docs

- lisp/magit-log.el
In order to restore the old window configuration after selecting a
commit or quitting.  Previously the window the diff buffer (if any)
lived on.
This still needs some testing.
> magit-log-select-{pick,quit}: use magit-mode-bury-buffer

- lisp/magit-imenu.el
- lisp/magit-log.el
- lisp/magit-notes.el
- lisp/magit-popup.el
- lisp/magit-status.el
I noticed that searching the man pages didn't work very often, so I thought I would fix it. Unfortunately, I didn't expect that there would be so many edge cases, so the end result looks awful. Perhaps I should put more comments in?
There are still two cases that aren't handled, though. The first is the `--` argument, which is sometimes absent and sometimes present as `[--]`, and the options that start with `++` (e.g., those in `magit-log-popup`). What would you like to happen with those? Should the `++` options have their own help pages?
I also made it a `user-error` to try and bring up the man page for an invalid option/switch.
> Fix man page search

- lisp/magit-ediff.el
I was getting an error when I tried to use `magit-ediff-stage` where emacs would try to call the list of tracked files as a function, resulting in an error like this:
Invalid function: (".gitignore" .....)
It seemed to me after a little investigation that this was happening because of `magit-ediff-stage` calling out to `magit-completing-read` with `(magit-tracked-files)` as the PREDICATE argument, when it should be COLLECTION (which was `nil`).
This pull request simply swaps those two arguments in that particular function call: now the call to `magit-completing-read` from `magit-ediff-stage` uses `(magit-tracked-files)` as the candidates, and `nil` as the predicate. An hour or two of casual use hasn't turned up any errors for me, so I thought I'd submit the change.
> swap args 2 & 3 in magit-ediff-stage's call to magit-completing-read

- lisp/magit-commit.el
- lisp/magit-diff.el
Following the discussion in #3199 I have implemented this like so:
* Separate the task of initially displaying the most suitable diff and toggling.
* Displaying the initial diff is done by `magit-commit-diff` alone.
* We considered to instead hand of that task to the black-box `magit-diff-while-committing` if we cannot decide based on `last-command`. Now that that function no longer is a black-box I was able to tell that that wouldn't have been a good idea :wink: 
* Toggling is done in `magit-diff-while-committing`.
* Toggling is only done if the buffer previously displayed "the other" diff.
* Previously we tried doing that too in most cases, but not in a reliable fashion and not in all cases.
* Else the most appropriate diff is displayed. This can become necessary if the user previously …
> Always display a diff while committing and improve toggling

- lisp/magit-apply.el
- lisp/magit-files.el
- lisp/magit-sequence.el
Currently, when `git am` fails, e.g, [if the patch was corruped by line wrapping](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28308#117), the sections magit presents are a bit unhelpful. It looks like this:
```
Applying patches
stop 0001
onto de8c782f34 Only match password prompts in part of line (Bug#28329)
```
where that funny "0001" represents the patch that failed. Git requires you to apply something to the index before `git am --continue` will succeed.
The first patch in this PR adds a title after the "0001", to make it more human friendly.
The next two allow applying it with `a`, although I'm not sure those represent the best way of doing that.
> Improve interface in case of 'git am' failure

- lisp/magit-utils.el
The `pcase-lambda` macro is not available in emacs 24.5.1 (e.g.,
provided by Ubuntu 16.04LTS), so we translate `pcase-lambda` to the
equivalent `lambda`/`pcase-let*`.
Closes #3255.
> Translate `pcase-lambda` to `lambda`/`pcase-let*`

- Documentation/magit.org
- Documentation/magit.texi
The binding and command name were incorrectly copy-pasted from `magit-submodule-init`
> Fix magit-submodule-deinit being copy-pasted

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-submodule.el
This variable name should instead be magit-module-sections-nested.
Closes #3257.
> Replace references to magit-insert-modules-nested

- lisp/magit-branch.el
...when magit-branch-read-upstream-first is nil.
Fixes #3268
> Fix return value from magit-branch-read-args

- Documentation/RelNotes/2.12.0.txt
- lisp/magit-git.el
- lisp/magit-process.el
I believe this should fix all the encoding issues when calling git:
- fix #3225
- fix #3111
- fix #2832
```
On windows-nt systems, the arguments to subprocesses must be encoded
in the current code-page.  But Windows git requires UTF-8 encoded
input.  The contradictory requirements mean we can't just set
default-process-coding-system to the right thing.  Therefore,
explicitly encode the arguments according to `w32-ansi-code-page', and
likewise encode input sent to git as `utf-8-unix'.
```
> Fix encoding of data and args for git subprocess on w32

- .travis.yml
- Documentation/RelNotes/2.12.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- Makefile
- default.mk
- lisp/Makefile
- lisp/magit-branch.el
- lisp/magit-collab.el
- lisp/magit-utils.el
- lisp/magit.el
The new command `magit-branch-pull-request` creates a local branch for the pull-request, adds a remote if necessary, and configures the branch to make working with pull-requests from outside collaborators just as easy as working with pull-requests whose branches have been pushed to the upstream repository.
`magit-branch-delete` has been taught to cleanup when deleting a "pull-request branch". That may involve deleting the "contributor's remote".
This is only a tiny step toward the goals described in #2972, but for people like me who review all pull-requests in Magit instead of by clicking around in a browser, it is a huge win.
Before I can merge this, I have to improve `ghub.el` somewhat. Most importantly it has to be made easier to create a new token but there are also some bugs.
> Make it easier to work with outside contributors' pull-requests

- Documentation/magit.org
- Documentation/magit.texi
The current description isn't quite accurate (the draft in this pr isn't either, yet). I also intend to check the implementation for correctness again and maybe make some improvements.
This is in response to #2877.
> Update documentation about the prefixes used to show in-progress rebases

- lisp/magit-repos.el
See #2961 and [this thread](https://lists.gnu.org/archive/html/emacs-devel/2017-10/msg00835.html) on `emacs-devel`.
> magit-repolist-columns: specify help-echo for narrow columns

- Documentation/RelNotes/2.12.0.txt
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-process.el
New face `magit-mode-line-process' increases the visibility of the
running process when Git is run for side-effects.
In addition, `magit-process-sentinel' now forces the redisplay of all
mode lines, as otherwise the `mode-line-process' value set by Magit
could remain visible in other windows after it had been cleaned up in
the selected window.
Closes #3284.
> Use a custom face for the process status indicator in the mode line

- lisp/magit-diff.el
#3298 introduced a couple of issues:
1. Use of the `file-attribute-size` accessor, which was only added in Emacs 26.
2. Passing the new `defcustom` `magit-diff-adjust-tab-width`, whose value could be `t`, to an arithmetic operator.
The first commit addresses these two issues. The second fixes what I believe to be a docstring typo, and the last two commits are suggestions for trivial logic simplification and optimisation.
Let me know if you'd like anything written/split differently, and thanks for this cool feature. :)
> magit-diff-tab-width fixups

- lisp/magit-branch.el
- lisp/magit-ediff.el
A couple of yes-or-no-p prompts were missing a space after the prompt.
> Add trailing space to yes-or-no-p prompts

- Documentation/magit.org
- Documentation/magit.texi
`make` does not succeed without `ghub` being available on the load path.
> Update manual installation to include ghub dependency

- lisp/magit-submodule.el
`magit-submodule-add` currently checks whether `ido-read-file-name` will be used by comparing with `eq` against `read-file-name-function`. However, as of Emacs 26, the `ido-everywhere` minor mode uses `add-function` rather than setting `read-file-name-function` directly. Thus, also check with `advice-function-member-p`.
On the other hand, I briefly tested `magit-submodule-add` with `ido-read-file-name` in Emacs 27.0.50 and it seemed to work as I expected, so maybe the kludge isn't necessary in newer Emacsen? I don't know what the original problem was though.
> magit-submodule-add: check for Ido advice

- Documentation/RelNotes/2.12.0.txt
- Documentation/magit.org
- lisp/magit-mode.el
- lisp/magit-process.el
Closes #3297
This provides an error state for `mode-line-process`, when the Git process exits with an error.
This includes an error face, a mouse tooltip with the error details, and a keymap so users can click to open the process log.
A by-product of this was a new general-purpose "repository-local" value cache which provides a more persistent alternative to buffer-local variables for storing data which is relevant to the repository in general.  I added the code for this in `magit-mode.el` primarily because that is where the `magit--default-directory` variable is defined, as this value is used to identify the repository.
Questions:
* I've made `magit-repository-local-repository` call `magit--not-inside-repository-error` if it can't establish a repository key. Is that sensible?
* I've …
> Use mode-line-process to indicate process errors

- lisp/magit-utils.el
I run command provided by `magit-emacs-Q-command` then Emacs enters the debugger and complains ghub is missing.
> magit-emacs-Q-command: Add ghub

- lisp/magit-process.el
It was possible for Magit to report an earlier error instead of the current error.
I noticed this on account of "Cannot rebase" not being recognised as an error message, so I've added that to the list.
> Bug fix for Git error summary messages

- lisp/magit-mode.el
Following on from https://github.com/magit/magit/pull/3314#issuecomment-356352148
* Use `equal` rather than `eq` for repository-local key equality (and using @npostavs's suggestion of `cl-delete`).
* Do not allow values to be cached when there is no current repository
> Repository-local fixes

- lisp/magit-remote.el
This adds the ability to specify a subject prefix for patches created by
the `git-format-patch` command.  Adding this ability is especially
useful when creating versioned patch sets to be mailed.
Regarding the shortcut key, I've debated either `P` or `S`.  I'm not
aware of any other good candidates.
Signed-off-by: Kenny Ballou <kballou@devnulllabs.io>
> Add subject-prefix to magit-format-patch

- lisp/magit-apply.el
- lisp/magit-bookmark.el
- lisp/magit-diff.el
- lisp/magit-ediff.el
- lisp/magit-git.el
- lisp/magit-imenu.el
- lisp/magit-log.el
- lisp/magit-mode.el
- lisp/magit-obsolete.el
- lisp/magit-process.el
- lisp/magit-refs.el
- lisp/magit-section.el
- lisp/magit-stash.el
- lisp/magit-submodule.el
- lisp/magit.el
- t/magit-tests.el
This is only a first step. The benefits will come once we start using generic functions.
> Define magit-section as a class instead of as a struct

- lisp/magit-collab.el
There's a good bit of functionality in Magithub that could be taken advantage of in Magit to be more DWIM. In vermiculus/magithub#201, I introduced thingatpt support for a few symbols like github-pull-request. I'm not totally sold on using the 'github' prefix here -- perhaps something more generic like 'gitforge' could be used instead.
This is a very simple patch right now and I expect it will change before it's merged. Specifically, I'm not sure how to handle maintaining the ability to choose a PR that is *not* the one at point. As it's set up right now, if point is on something that defines github-pull-request, the user won't have the opportunity to override that value.
> Use thing-at-point to guess which GitHub pull request is desired

- lisp/git-commit.el
I'm not sure about my commit message if it should be more elaborate.
Guess that one line is enough?!
I customized `core.commentchar` as sometimes I just put
`#123` as a reference to a issue in it's own line so I
set comment char to `;`.
> git-commit-turn-on-flyspell: respect customized comment character

- lisp/git-commit.el
When attempting to invoke `git-commit-prev-message` or `git-commit-next-message` in a buffer without comments, the functions would fail with the message:
git-commit-prev-message: Search failed: "^#"
Such a buffer could be the result of a `prepare-commit-msg` git hook which does not emit any comment lines.
The rest of the code was already prepared to handle this scenario, so just fix the `re-search-forward` invocation to not error when the regexp was not found, and allow the caller to handle the failure.
> git-commit-prev-message: Fix error in buffers without comments

- lisp/magit-git.el
- lisp/magit-process.el
This should fix #3345. The first two commits fix some other issues that I noticed while looking at that bug (https://github.com/magit/magit/issues/3345#issuecomment-360813859 and https://github.com/magit/magit/issues/3345#issuecomment-361331270 (bottom half)).
I want to double check the thing about tramp using `process-environment` though, as I would have assumed that `tramp-remote-process-environment` would be used instead...
> Don't apply w32 env hacks for remote repositories

- lisp/magit-submodule.el
`git submodule update` allows the --recursive flag but when set in the popup it does not get passed down to it since it is filtered out. This PR simply adds `--recursive` to `update`'s filter list.
> Allow 'submodule update' to use --recursive switch

- lisp/magit-refs.el
The pcase-lambda macro is not available in emacs 24.5.1 (e.g.,
provided by Ubuntu 16.04LTS), so translate pcase-lambda to the
equivalent lambda/pcase-let.
> Translate `pcase-lambda` to `lambda`/`pcase-let`

- README.md
The CONTRIBUTING.md link in the README.md returns 404.
* Point the contrib link to it's new location
> Fix CONTRIBUTING.md link in README.md

- Documentation/RelNotes/2.12.0.txt
In addition, I wasn't certain how to fix this one:
> * When selecting a fixup target then the log graph, which makes it
>   less likely that you attempt to modify a merged commit, which would
>   result in the merges being lost when rebasing.  c0209c74d
Although I suspect it was intended to say something like:
> * When selecting a fixup target the log graph is displayed (regardless
>   of the default options), which makes it less likely that you attempt
>   to modify a merged commit, which would result in the merges being
>   lost when rebasing.  c0209c7
Other oddities I noticed (but maybe I've just forgotten conventions) were " ff" suffixes following some hashes (maybe indicating a fast-forward merge, but it wasn't clear to me if that ought to be in the release notes). e.g.:
> * Jumping …
> Fix typos in release notes for v2.12.0

- lisp/magit-git.el
- lisp/magit-log.el
aac74cc466c40adbbeba373d85e13f72b175bc5e added support for `magit-log-buffer-file` in dired buffers, but `default-directory` returns the full directory path instead of relative path. 
This change adds dired support for `magit-file-relative-name`, tell me if this is not desirable.
Calling `magit-log-buffer-file` in a dired buffer sets:
```elisp
(magit-log-arguments)    ;; => (("-n256" "--graph" "--decorate") ("~/code/magit/lisp/"))
```
expected:
```elisp
(magit-log-arguments)    ;; => (("-n256" "--graph" "--decorate") ("lisp/"))
```
> Use relative paths for dired buffers

- Documentation/magit.org
- lisp/magit-blame.el
- lisp/magit-diff.el
- lisp/magit-log.el
Calling `magit-log-buffer-file` interactively with an active region would previously call `magit-log` with a corresponding `-L<beg>,<end>:<file>` argument, to display the log of the selected region. This currently does not work for any files that aren't in the base dir of the repo.
It looks like this function was changed in 293bf0d6c to only enable `-L` if the file is a regular file, using `file-regular-p`. However, it calls `file-regular-p` with the filename *relative to the repo's root directory*, but the `default-directory` of this command is the dir that the file is located in.
e.g. in the repo `/home/user/repo`, if editing the file `/home/user/repo/some/example.txt` with an active region, calling `magit-log-buffer-file` would end up checking `(file-regular-p "some/example.txt")`, …
> magit-log-buffer-file: Use absolute filename in call to file-regular-p

- lisp/magit-extras.el
Avoid an error where we try to open "git.exe/gitk", which triggers Tramp to try to extract a file "gitk" from an archive "git.exe", which causes an error, "package 'tramp-archive' not supported".
To reproduce the error (on Windows), have magit installed, then run "emacs -Q", then:
M-x package-initialize RET
M-x load-library RET magit-extras RET
> magit-gitk-executable: fix default gitk filename, on Windows.

- lisp/magit-blame.el
This typo from 6d7127d6e37f48d7256c954cf36f98a82d6a23f5 reintroduced issue #1780.
> magit-blame-put-keymap-before-view-mode: Fix typo

- lisp/magit-commit.el
- lisp/magit-extras.el
Fixing a typo. A cosmetic-only change for consistency.
> Fix typo: reselve -> reshelve

- lisp/git-rebase.el
This adds the “noop” operation to the “rebase” menu, and colours this instruction in the “git rebase” buffer.
> git-rebase.el: noop-related changes

- Documentation/RelNotes/2.13.0.txt
- lisp/magit-reset.el
Closes #3438 
* Makes the prompts for all magit-reset-* commands more explicit about what will be done.
* Hard resets are further highlighted by making the word "Hard" bold.
The new prompts are more verbose than I originally suggested in #3438, but I think it's worthwhile verbosity.
> Make the reset command prompts more explicit

- Documentation/RelNotes/2.13.0.txt
- lisp/magit-blame.el
Because the time variable is an Unix time which is not related to time zone,
we don't have to update time according to time zone.
If time-format contains the time zone symbol ( %z or %Z ),
use tz-in-second to format the time in committer time zone or author time zone.
If time-format doesn't contain the time zone symbol ( %z or %Z ),
assign tz-in-second to nil to format the time in local time zone.
> magit-blame--format-time-string: Correct timezone handling

- lisp/magit-extras.el
Under windows-nt, I was getting error messages on trying to use commands defined in `magit-extras.el`.  Digging in, it was the `defcustom` of `magit-gitk-executable` causing the problem.  It might be something unusual in my setup (which I'm not in front of right now), but the `which` was not finding `gitk.exe`, and a `nil` was getting through to `file-executable-p`, about which it complained.
This PR puts in a check for `nil`, which avoids the error and so fixes things for me.
> Avoid error if gitk not found on windows-nt

- lisp/magit-mode.el
`magit-mode` turns off `linum-mode` and `nlinum-mode` if they are on; in emacs 26 we now have `display-line-numbers-mode`, which should get the same treatment.
> Turn off display-line-numbers-mode if on

- Documentation/RelNotes/2.13.0.txt
- lisp/magit-git.el
Fixes #3457.
I somewhat arbitrarily chose 0.5 seconds as the default timeout.
By the way, I'm not sure exactly how I got my repo into a state where `magit-get-previous-branch` can take a long time (I still have it in that state currently though). I tried a test script which creates and deletes many branches, but that doesn't seem to do the trick.
> magit-get-previous-branch: Add timeout

- lisp/magit-extras.el
1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>g</kbd>
3. <kbd>C-M-i</kbd>
* Expected result: Pop to Dired buffer visiting Magit's directory.
* Actual result: Pop to Dired buffer visiting parent of Magit's directory.
This is caused by `magit-dired-jump` appending `"/."` to directory names, which `dired-jump` expands to a file, rather than directory, name. A subsequent `file-name-directory` yields the parent, rather than current, directory.
Given that `dired-jump` defaults to `default-directory`, I think directory name manipulation can be removed from `magit-dired-jump` altogether, as in the proposed patch.
> magit-dired-jump: Don't append slash to directory

- lisp/magit-utils.el
* Helm now handlers completion functions differently.  We need to account for that in order to get fuzzy matching.  #3476 
* Ivy now sorts alphabetically by default.  Whether this commit (or some other fix) needs to be included depends on the outcome of abo-abo/swiper#1611
> completion: Update for latest helm/ivy changes

- lisp/magit-log.el
`which-function` uses `add-log-current-defun` as one of many helpers so it
should only improve the experience.
I've tried it with lua files and it works good enough. elisp work equally well as before so far.
> Use which-function instead of add-log-current-defun

- lisp/magit-log.el
- lisp/magit-merge.el
- lisp/magit-mode.el
- lisp/magit-status.el
- lisp/magit.el
Please see the commit messages, give this a try, and then report on whether you like these changes or not.
>  Change order and initial visibility of logs in status buffer

- lisp/magit-log.el
This addresses #3523; it resolves a bug in which `magit-log-trace-definition` doesn't work with Go methods on a pointer receiver (and in general, anything for which `which-function` returns a string containing a regular expression metacharacter: the issue is that git expects a regular expression).
I was a bit concerned that `regexp-quote` might not be suited to
escaping the regular expressions git expects, but it appears to do the
right thing: escaping `[*.\?+^$` but not `(`.
> Quote regexp-meaningful characters in function name

- lisp/git-commit.el
Should fix #3491. I think we should additionally move the cygwin filename hack from `git-commit-setup` to `find-file-not-found-functions`, but I want to make sure just the `git-commit-setup-font-lock` change on its own will fix the original problem.
> git-commit-setup-font-lock: Don't fail in non-existent directory

- lisp/magit-diff.el
It seems a side effect of calling `hack-dir-locals-variables` can mess up the point while inserting, here's a before screenshot:
> Fix revision message placement in case of risky var query

- lisp/magit-process.el
Make this behaviour configurable via magit-process-display-executable-basename.
The path to the git-executable might be quite long on some systems. It then eats
up a large part of the modeline, hiding more interesting information like the
git-subcommand that has been run. With this change, an option is introduced to
show only the executable basename. By default, the old behaviour is preserved.
> Show executable-name without directory.

- lisp/magit-git.el
> magit-git-executable: Remove obsolete compatibility kludges

- lisp/magit-commit.el
- lisp/magit-log.el
And stop hard-coding `--graph' in `magit-commit-squash-internal'.
This makes it possible for users NOT to use `--graph' if that has
negative effects on performance.  On the other hand it also means
that all uses of `magit-log-select' now show the graph by default,
but the latter might actually be beneficial too.
Re #3559.
> magit-log-select-arguments: add --graph to default value

- lisp/magit-collab.el
The `separator' argument of `split-string' should be in second
position.
Fixes #3572
> magit--github-url-p: fix a bug in github enterprise handling

- lisp/magit-submodule.el
- lisp/magit-utils.el
I haven't tested any of this yet but am publishing it now to prevent others from implementing and reviewing things that won't be merged.
* `magit-submodule-add: Run asynchronously` in response to #3584.
This is a recurring pattern and should be abstracted, but there is no hurry to do so.
* `magit-submodule-remove: New command`
The major differences to the implementations suggested in #3582 and #3583 are 
* It refuses to do anything if there are uncommitted changes.
* It does *not* remove the git directory of the submodule. If the gitdir is located in the working tree, then it is first moved into the gitdir of the super-repository. Removing a gitdir is very dangerous.
* An additional command `magit-submodule-purge-gitdir` could be added which does remove a gitdir that is no longer …
> New and improved module commands

- .github/PULL_REQUEST_TEMPLATE
- Documentation/magit.org
- Documentation/magit.texi
Fix single-letter spelling mistakes in the manual.
> The latter has to be generate[d] from the former.
Please note that your GitHub PR template also has a spelling mistake, above.
> Spelling fixes to the manual.

- lisp/magit-apply.el
- lisp/magit-git.el
Provide a more informative error message when a user tries to reverse binary files from a revision or diff buffer.
Closes #3625.
> magit-reverse-files: Extend binary file check

- lisp/magit-diff.el
Fix incorrect (copy'n'paste?) doc string for
`magit-diff-context-highlight` font face
> magit-diff.el:  fix font face documentation string

- Documentation/magit.org
- Documentation/magit.texi
wrong variable name
(needs .texi; I get `Cannot open load file: No such file or directory, org-man` when I try to make it)
> doc typo: magit-revision-show-gravatar→magit-revision-show-gravatars

- Documentation/RelNotes/2.91.0.org
- lisp/magit-log.el
Use git-when-merged to help users ask "When was this commit merged
into this ref?" and "Assuming this commit was developed in a topic
branch, what were the other commits in that topic?".
> magit-log-merged: New command

- Documentation/RelNotes/2.91.0.org
- lisp/magit-commit.el
Fix  #3674 by explicitly plumbing down the last optional argument to `magit-log-select`.
TL;DR: there could be a better way to do this but I couldn't find it.
I did read the code of `magit-log-goto-same-commit`, and its fallback logic did sound a little bit like what we want to use to me. However, it appears to work based on the `magit-previous-section` variable, which is only called when setting up a new buffer afaict.
> On instant squash/fixup, keep commit cursor is at

- Documentation/RelNotes/2.91.0.org
- Documentation/magit.org
- lisp/magit-refs.el
- lisp/magit-section.el
- lisp/magit-submodule.el
- lisp/magit-utils.el
I am undecided whether to enable this by default and if so what style
to default to.  Enable it for now on the development branch, so that
users notice and get a chance to comment here before the next
release.
> Visibility indicators

- Documentation/RelNotes/2.91.0.org
- lisp/magit-branch.el
- lisp/magit-diff.el
- lisp/magit-extras.el
- lisp/magit-git.el
- lisp/magit-process.el
- lisp/magit-sequence.el
```
As of 296f8dc7 (magit-diff-type: Fix case when the HEAD is used as
RANGE, 2018-09-13), we use `magit-rev-eq' to check whether RANGE
resolves to HEAD to avoid classifying `git diff HEAD'-equivalent
output as `committed'.
That fix introduced another edge case.  `magit-rev-eq' calls
`magit-rev-verify' on each argument, which returns the first line of
`git rev-parse --verify'.  In the case of a range A..B, the standard
output spans multiple lines, with first line being B's hash and the
second being "^A-hash".  This means that `(magit-rev-eq "A..B"
"HEAD")', where B resolves to "HEAD", will return true, and
`magit-diff-type' will incorrectly classify the diff as either
`unstaged' or `staged'.
Avoid this misclassification by confirming that RANGE isn't actually a
range before passing it to …
```
> magit-diff-type: Guard rev-eq call to fix range edge case

- lisp/magit-log.el
Fixes magit-log-move-to-parent
> Predicate should use `it`, not section (which never changes)

- lisp/magit-clone.el
The git clone command need credentials in order to perform on private repositories.
> magit-clone: execute magit-credential-hook

- Documentation/RelNotes/2.91.0.org
- lisp/magit-section.el
The interactive form and args did not match up, so using a prefix interactively did not cause the ident to be displayed, but rather the vector (which is not useful for magit-status-initial-section).
> Fix: (magit-describe-section-briefly) Display ident interactively

- lisp/magit-blame.el
Hi!
`magit-blame-echo` never quite worked for me: I did get thin lines
separating chunks belonging to different commits, but no message in
the echo area.
I poked around `magit-blame.el` and found a few things that look like
impedance mismatches to me:
- `m-b-maybe-show-message` checks the current style for the
`show-message` key, but `magit-blame-echo-style` is set to the
`lines` visualization style, which only contains `show-lines`.
- `m-b-maybe-show-message` looks for the `'heading` symbol in the
commit alist, but the keys returned by `m-b--commit-alist` are
strings, the first of which is `"summary"`.
- `assq` uses `eq` to browse alists, which tests "Lisp
object"-equality; to match on a string such as `"summary"`, one must
use `assoc`, which uses `equal`.
This commit is pretty much …
> Make magit-blame-echo actually echo the commit summary

- lisp/magit-utils.el
This allows the bitmaps to be shown when emacs is started with `emacs --daemon` and a graphical emacsclient frame is later created.
(I realize this may not be the right solution, but figure it's simple enough that I might as well start by putting it out there.)
> Unconditionally initialize fringe bitmaps

- lisp/magit.el
Without it, pressing "i" or "I" in magit-status shows an error message:
Wrong type argument: commandp, magit-gitignore
> Add missing require for magit-gitignore

- Documentation/magit.org
- lisp/magit-section.el
Closes #3726.
I've omitted the call to `set-window-buffer` which was suggested in https://github.com/magit/magit/pull/3679#issuecomment-441747653 on the basis that, so far as I can see experimentally, it's unnecessary in this case -- `magit-mode` and its derivatives are called before the buffer is displayed, so I believe there is no need to forcibly re-display the buffer at this point.
> Document how to set the fringe width for the visibility indicator

- lisp/magit-diff.el
This change eliminates a strange feedback loop that occurs when buffer-list-update-hook is used to make a debounced (idle-timer based) call while a region is active in magit. See also the discussion in #3738.
> magit-diff.el: Inhibit buffer-list-update-hook in diff-hunk-region-patch routine.

- lisp/magit-branch.el
Currently if you delete the only local branch from a pull request remote, you are prompted to also delete the remote corresponding to that PR. However if you press `n` at this prompt, deletion of the branch is aborted. Solution: pass `t` as the value of the `noabort` parameter to `magit-confirm` for the prompt in question.
As an aside: at this point I've been using Magit daily for over five years. Thank you for the continued dedication and hard work put into this project.
> magit-branch-delete: Don't abort when preserving PR remotes

- Documentation/magit.org
- Documentation/magit.texi
Fix harmless typo in documentation (magit.org): "turn of" => "turn off".
> Fix harmless typo in documentation: "turn of" => "turn off"

- Documentation/RelNotes/2.91.0.org
- lisp/magit-bisect.el
- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit.el
Git v2.2 was released more than four years ago.
I announced a long time ago that I would drop support even for
versions before v2.4.  I dropped support for versions before
v2.0 more than half a year ago and nobody complained about it.
Even Debian stable has v2.11 now, and while Debian oldstable
only has v2.1, v2.11 is available from jessie-backports.
> Require at least Git v2.2.0

- Documentation/RelNotes/2.91.0.org
- lisp/magit-diff.el
- lisp/magit-merge.el
- lisp/magit-stash.el
The infix argument is on level 5 of the diff transients for now.  It
has to be made available by the user for each transient using "C-x l".
For now the colors specified in `ansi-color-map` are used.
> diff: Add basic support for --color-moved

- lisp/magit-push.el
I believe --follow-tags should have a `-` prefix and not `=` as it doesn't set an argument.
> magit-push: Use -t for --follow-tags

- Documentation/RelNotes/2.91.0.org
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-diff.el
Let the user configure which ugliness they prefer when showing a
commit from a log that uses --follow: empty diffs or ignoring the
log's file restriction.
Closes #3680.
> magit-revision-filter-files-on-follow: New option

- lisp/magit-diff.el
The diff transients gained --color-moved in 9d0e65ee (diff: Add basic
support for --color-moved, 2019-03-08).  Add the related option
--color-moved-ws.  This option, particularly its mode
allow-indentation-change, increases the number of scenarios where
--color-moved is useful.
--color-moved-ws accepts a comma-separated list of modes, so we could
read these with magit-completing-read-multiple.  But there aren't
many (if any) useful combinations, so let's instead define the reader
with the more convenient magit-read-char-case.
> diff: Support --color-moved-ws

- lisp/magit.el
The key `Y` (`magit-cherry`) is bound in the magit status buffer, but not the dispatch transient. It is applicable to both scenarios. I often find my self going `c-x M-g Y` only to have it tell me that it is unbound. Seems it should be made available.
> magit-dispatch: Add Cherries

- Documentation/RelNotes/2.91.0.org
- lisp/magit-branch.el
When deleting a remote ref fails, we fall back to removing the local
remote-tracking ref because a common reason for the push to fail is
that the ref no longer exist on the remote.  But it may fail for other
reasons (e.g., can't connect to the remote or a non-zero exit of the
pre-receive hook), and we shouldn't remove the local tracking ref in
these cases.
One way to tighten the check would be to search the process buffer for
"unable to delete 'BRANCH': does not exist".  (We'd need to search for
each ref with a tailored message because we wouldn't want to remove
the remote-tracking refs for multiple refs when the push failed
because one ref does not exist.)  This method relies on the message
being stable and wouldn't work for some users because that message is
marked for translation. …
> magit-delete-remote-branch-sentinel: Decrease false positives

- lisp/magit-sequence.el
The transient library doesn't have a function called `transient-read-natural-number-N+`.  This seems to be a typo for `transient-read-number-N+`, which does exist, and makes `A - m` work as expected rather than suddenly closing the transient.
> Fix typo in `magit-cherry-pick:--mainline`

- lisp/magit-sequence.el
The perl-based editor for magit-rebase-{edit,reword,remove}-commit
assume that the target commit is the first item in the rebase todo
list.  If --rebase-merges is given, this may not be the case depending
on the branch structure.
Update the perl command to match against the target commit.
> rebase-interactive: Adjust perl editor for --rebase-merges

- lisp/magit-branch.el
This PR fixes the `spin-off` and `spin-out` shortcut.
As stated in the manual since the [`spin-out` command](https://github.com/magit/magit/commit/b10bf92a2e5d2f7443656c482b27d58b49f3be9f#diff-67c0d4a7440114596845f478f8ed4877R4436), the shortcut should be `b S`, but [this commit](https://github.com/magit/magit/commit/b10bf92a2e5d2f7443656c482b27d58b49f3be9f#diff-7cd00c1c77155001edfa4602112b9195R217) overwrite the `b s` command which was previously used for `spin-off`.
I noticed this behavior by trying to `spin-off`with `b s` after having upgraded my Magit (the branch was not checked out).
I've also moved the `spin-out` command in the `Create` column.
> fix spinoff/spinout shortcuts

- lisp/magit-stash.el
- lisp/magit-submodule.el
Hello!
I recently started getting errors from git when trying to make stash(Magit shortcut: **z z**):
```
128 git … reset --hard HEAD
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
My PR is  attempt to fix this.
I'm not a sophisticated git user, so comments and corrections are welcome.
> Fixing git error while trying to stash

- lisp/magit-fetch.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-obsolete.el
- lisp/magit-pull.el
- lisp/magit-push.el
- lisp/magit-remote.el
- lisp/magit-repos.el
- lisp/magit-sequence.el
- lisp/magit-status.el
The most important user visible changes are:
* `b u` can only be used to select an existing branch as the upstream. `p u` has to be used to push to a new remote upstream.
* The headers about the upstream and push-remote in the status buffer now display more information when these remotes are not completely usable, explaining why that is so.
* The descriptions of "configure upstream/push-remote before operating on it" are more informative now when the remotes are not completely usable, but not as informative as the status buffer headers.
* Only `p u` "push to upstream" can be used to create a configured but so far non-existent upstream/push-remote. All other commands that can "configure upstream/push-remote before operating on it" can now only use a branch that is known to exist.
* `f u` …
> Improve handling of upstream and push-remote

- lisp/magit-status.el
To be consistent with the "Head:" ordering when `magit-status-show-hashes-in-headers` is enabled (seems to have happened in 86c095ab)
Before:
After:
Haven't looked into adding a regression test yet but I can if necessary.
> Fix magit-status "Merge:" header commit+ref order

- Documentation/magit.org
- lisp/magit-autorevert.el
From oldest to newest, the three commits are in order of decreasing importance and increasing controversiality:
1. Fix a logic error in `auto-revert-buffers--buffer-list-filter` which used `auto-revert-buffer-list-filter` as a variable, rather than a function.
2. Audit auto-revert-related docs for typos, grammar, and inconsistencies (such as `auto-revert-mode` being the only mode labelled a Command rather than a User Option).
3. Minor `magit-autorevert.el` code touch-ups.
I'm happy to reword/amend commits, but feel free to also make any changes you see fit yourselves. Note that someone else will have to update the Texinfo manual for me.
Thanks.
> Various auto-revert fixes

- Makefile
- lisp/magit-pkg.el
make bump-version will now add 
``` lisp
:keywords
'("git" "tools" "vc")
```
to `lisp/magit-pkg.el`
> Added keywords for pkg file

- lisp/git-rebase.el
I noticed that the lower lines of the rebase buffer (which showed the keybindings for pick, reword, edit, squash, fixup, and exec) almost always had a strikethrough with no keybinding, even though the key worked in the buffer. I started investigating and it seemed pretty weird-- when I edebugged `git-rebase-mode-show-keybindings` and watched it populate the buffer, it worked just fine and all the bindings were there, but then when I tried to rebase without edebug again they would be crossed out again.
Eventually, this behavior bagan to make sense to me when I carefully read the docstring of `where-is-internal`. For its second argument, which is optional, the docstring reads:
```
If KEYMAP is a keymap, search only KEYMAP and the global keymap.
If KEYMAP is nil, search all the currently …
```
> git-rebase-mode-show-keybindings: Get bindings from mode map

- lisp/magit-worktree.el
If `magit-worktree-branch` is called interactively, it will read a `start-point` but ignore it. Instead it will use the current branch. This PR fixes that.
> magit-worktree-branch: Fix bug where start-point is ignored

- lisp/magit-pull.el
- lisp/magit-push.el
The description strings of `magit-pull-from-pushremote` and `magit-push-current-to-pushremote` were mixed: `magit-pull-from-pushremote` ended the sentence with "push there", and `magit-push-current-to-pushremote` ended the sentence with "pull from there".
> Fix pull/push push remote strings

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-commit.el
- lisp/magit-diff.el
- lisp/magit-extras.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-utils.el
I hope users will notice this change because the changed feature is a very useful, i.e. I hope people use this. I also expect that it will take some users by surprise. The change in behavior is this:
```diff
* RET (magit-diff-visit-file) on uncommitted change:
jump to position in file in worktree
* RET on committed change:
jump to position in blob from commit
-  * except RET on HEAD change:
-    jump to position in file in worktree
-    therefore it is impossible to jump to a HEAD blob
* C-RET (magit-diff-visit-file-worktree) on any change:
jump to position in file in worktree
```
It might take some time for muscle memory to adjust, but being able to jump to a blob from HEAD is a win.
> Support going from diff to a blob from HEAD

- Documentation/RelNotes/2.91.0.org
- lisp/magit-process.el
- t/magit-tests.el
As I said in https://github.com/magit/magit/issues/3843#issuecomment-485944696
> We already strip `\r` in `magit-process-filter`; the correct fix would
> be to shuffle the code around so that it happens before password
> prompt checking instead of after.
Fixes #3843.
> magit-process-filter: Strip \r *before* checking prompts

- lisp/magit-autorevert.el
As of the following Emacs version:
```
In GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
of 2019-04-30 built on thunk
Repository revision: 826f1e260121edc5185e0ed3fa20a781fbddc9a2
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description: Debian GNU/Linux buster/sid
```
the variable `auto-revert-buffers-counter` no longer exists. This gives rise to the following error:
1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>C-f</kbd>`Makefile`<kbd>RET</kbd>
3. <kbd>RET</kbd><kbd>C-x</kbd><kbd>C-s</kbd>
4. <kbd>C-x</kbd><kbd>g</kbd>
5. <kbd>k</kbd><kbd>y</kbd>
```
Debugger entered--Lisp error: (void-variable auto-revert-buffers-counter)
(cons (or (magit-toplevel) 'no-repo) auto-revert-buffers-counter)
(setq …
```
> magit-autorevert.el: Define own counter variable

- lisp/magit-diff.el
- lisp/magit-ediff.el
- lisp/magit-files.el
This is a sequel to #3848, which cleaned up some of the code that is being reused here. This is all still a bit messy and I plan to clean it up once `git-handler.el` (#2958) is ready. The plan was to implement that library first, but I got stuck early on and concentrated on other things. If I had known that taking some big steps here would be a fairly small amount or work, even without implementation that library first, I probably would have done this much earlier.
I think it's quite a big deal to be able to move between different versions of some code (as a file or a diff) without losing the location. That being said, there probably still are bugs and places where we *could* preserve the location but don't do so yet. Even so this is a big step toward taking care of  #2995. Well at least …
> Goto to the same location within another version and/or view of this file/diff

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-mode.el
As discussed in #3862, with this pull request, a double prefix argument given
to `magit-mode-bury-buffer` will also kill all other Magit buffers associated
with the current project.
I've chosen not to add a new `magit-bury-buffer-function` implementation which
would have that feature (as you've suggested) but just do it directly in
`magit-mode-bury-buffer` so that it will work no matter which
`magit-bury-buffer-function` people are using.
> Kill associated Magit buffers with C-u C-u q

- lisp/magit-files.el
Noticed a regression on the MELPA magit when I updated today: `magit-find-file-other-window` would always open up a new frame. Fix was trivial.
Commit message:
> Commit 8e380e892086e9 ("magit-find-file--internal: New function") passes the wrong switch-to-buffer func through to magit-find-file--internal, which caused magit-find-file-other-window to act like its other-frame sibling.
(Don't know if it matters for magit, but my copyright assignment is on file with the GNU.)
> magit-find-file-other-window: use correct switch-to-buffer fn

- lisp/magit-utils.el
Since the REQUIRE-MATCH argument to `magit-completing-read` means that an empty string is not a valid completion (unlike in `completing-read`), I've modified the call to `ido-completing-read+` to prevent it from accepting an empty string from the user when REQUIRE-MATCH is non-nil. This means that magit's ido completion will no longer offer the empty string as the first completion option, and pressing RET without typing anything will accept the first choice.
<strike>If there actually *is* a case where the empty string is desired as the default choice, then the only way to specify that now is to explicitly pass the empty string (not nil) as the default. This might be desired if the calling function *really* wants to make sure the user is intentionally selecting an option instead of just …
> Give require-match the correct meaning in magit-ido-completing-read

- Documentation/RelNotes/2.91.0.org
- lisp/magit-bisect.el
- lisp/magit-blame.el
- lisp/magit-branch.el
- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-process.el
- lisp/magit-pull.el
- lisp/magit-push.el
- lisp/magit-reflog.el
- lisp/magit-refs.el
- lisp/magit-remote.el
- lisp/magit-repos.el
- lisp/magit-reset.el
- lisp/magit-section.el
- lisp/magit-sequence.el
- lisp/magit-stash.el
- lisp/magit-status.el
- lisp/magit-submodule.el
- lisp/magit-transient.el
- lisp/magit-utils.el
- lisp/magit-worktree.el
https://github.com/magit/magit/issues/2821#issuecomment-253082085 says
> `whitespace-mode` uses font-lock to do its thing. Magit does not use font-lock to to add faces/colors to its buffers. That makes them incompatible because turning on font-lock removes all faces keeping only those that it adds itself.
> 
> The only thing we could do is to somehow prevent `whitespace-mode` from being turned on in magit buffers.
But it looks like all that's needed to make magit compatible with `whitespace-mode` is `s/'face/'font-lock-face/` (I've only done a quick search&replace without reformatting, if this approach is okay I can go back and reformat lines which got longer as needed). The Elisp manual sort of mentions this in [(elisp) Precalculated …
> make magit-mode compatible with whitespace-mode

- lisp/magit-diff.el
Fixing a simple bug with magit-diff-switch-range-type
Addresses Issue #3898
> Fix diff-switch-range-type.  replace-match requires match # to fix

- lisp/magit-bookmark.el
Make it possible to trigger loading of magit when visiting a magit-status bookmark
> Add autoload cookies for `magit--handle-bookmark`

- Documentation/magit.org
- Documentation/magit.texi
Option magit-revision-header-format is actually called
magit-revision-headers-format.
> Fix typo magit-revision-headerS-format

- lisp/magit-blame.el
- lisp/magit-diff.el
- lisp/magit-section.el
Since Magit no longer supports Emacs version lower than 25, these conditions should be removed.
> Remove conditions for Emacs version lower than 25

- lisp/git-commit.el
Change log entries are customarily unindented[1].  In `git-commit-mode`, however, `adaptive-fill-regexp` picks up leading asterisks `"* "` in change log entries, which are subsequently interpreted as a fill prefix of 2 spaces.  Thus, entries like the following:
```
* file: very long description...
```
are "indented" to column 2 when filled:
```
* file: very long
description...
```
Instead of messing with `adaptive-fill-mode`, the simplest way to avoid this `fill-prefix` by default (but still allow users to enforce it by manually indenting the paragraph's 2nd line) is to enable `fill-indent-according-to-mode`, as was recently done in Emacs' `python-mode` for bug#36056[2].
[1]: `(info "(standards) Style of Change Logs")`
https://www.gnu.org/prep/standards/html_node/Style-of-Change-Logs.html …
> git-commit-setup-changelog-support: Fix filling

- Documentation/RelNotes/2.91.0.org
- lisp/magit-bisect.el
- lisp/magit-blame.el
- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-process.el
- lisp/magit-pull.el
- lisp/magit-push.el
- lisp/magit-reflog.el
- lisp/magit-refs.el
- lisp/magit-remote.el
- lisp/magit-repos.el
- lisp/magit-reset.el
- lisp/magit-section.el
- lisp/magit-sequence.el
- lisp/magit-stash.el
- lisp/magit-status.el
- lisp/magit-submodule.el
- lisp/magit-utils.el
- lisp/magit-worktree.el
This is a continuation of #3840 which was prematurely merged (and then unmerged, but github doesn't realize that part).
> So I think [all functions that return a propertized string] should use both `face` and `font-lock-face`, because a 3rd party package might insert the string into a buffer without font lock (like transient, where we want `face`), or a buffer with font lock searching enabled (where we would want `font-lock-face`).
I've added a `squash!` commit which does that. Though it occurs that it might be simpler for future maintenance to just always use both `face` and `font-lock-face` regardless of circumstances.
> make magit-mode compatible with whitespace-mode and other font lock using modes (v2)

- Documentation/RelNotes/2.91.0.org
- lisp/magit-apply.el
When applying a hunk or a region of a hunk that is not the first hunk
from the file, the line number in the header for the new start
position will often be incorrect because it accounts for content of
the ignored hunk(s) from above.  This usually isn't problematic
because there is enough context for 'git apply' to locate the
appropriate spot, but, in some cases where the context is too
repetitive to identify the location, it can lead to incorrect staging.
Note that the problem here is simpler than the one that 'git add -p' needs
to solve because, due to Magit's restrictions on what makes a valid
selection, we know that the hunks are contiguous and from the same
file.
Re: #3924
> apply: Adjust hunk line positions for partial application

- Documentation/RelNotes/2.91.0.org
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-obsolete.el
- lisp/magit-repos.el
Allow specifying arbitrary flags and predicates in custom order.
With the default value of magit-repolist-column-flag-alist, this is
fully backward compatible with the original magit-repolist-column-dirty,
which is also preserved as an obsolete function alias.
[This is a continuation of #3936]
> magit-repolist-column-flag: Replacement for magit-repolist-column-dirty

- Documentation/RelNotes/2.91.0.org
(magit-status-here) is in C-c M-g g; C-c M-g s is (magit-stage-file).
> Fix keybinding typo in 2.91.0 release notes

- lisp/magit-blame.el
- lisp/magit-log.el
- lisp/magit-stash.el
These functions did not show the correct objects when point was moving quickly
through the list. The object to show was stored when the command to go to the
next item was issued for the first time and then displayed later after a timer
elapsed.
This is inadequate when moving through the list quickly: By the time the objects
are shown point is actually further ahead so there is a discrepancy between the
shown object and the place where point is.
This commit also fixes a small bug in magit--maybe-update-blob-buffer which was
looking at the wrong variable.
> Fix ...-maybe-update-... functions.

- lisp/magit-mode.el
Syntactic font lock automatically fontifies syntactic elements such as strings in Magit diffs using the `face` property.  This clashes with Magit's manual application of the `font-lock-face` property.
Fixes #3950.
> magit-mode: Disable syntactic font lock

- lisp/magit-log.el
Support passing --branches=<pattern> to git-log.
Tentative fix for #3957. I'm not sure if having an action is the best way to do what I did. I think maybe an infix argument would be better but then it may conflict with other usages of `--branches`.
> Support passing --branches=<pattern> to git-log [#3957]

- lisp/git-rebase.el
the symbol 'all instead of '(all) previously
'(all) is still supported though, but if a user set it to 'all, magit
will fail to load.
> async-bytecomp-allowed-packages value can now be

- Documentation/RelNotes/2.91.0.org
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-worktree.el
I noticed that there exists a [`git worktree move` command](https://git-scm.com/docs/git-worktree#Documentation/git-worktree.txt-move) in the git worktree documentation, and figured it would make a good addition to the repertoire of existing magit worktree commands.
Since having implemented it, I've actually integrated it into my workflow—largely as a mechanism to move worktrees that I have accidentally created where they ought not to be.
> Add magit-worktree-move

- lisp/magit-commit.el
Hi!
I usually commit with some changes.
Adding all changes without any confirming helps me to easy commit.
So I added 'stage new option to stage anything without confirm.
> Add new option, `stage` for magit-commit-ask-to-stage

- lisp/magit-mode.el
`file-exists-p' calls tramp functions for remote files which can cause
Emacs to hang if the remote host is no longer accessible.
It looks like this bug has been addressed a few times before (#1472 #3087) but subsequent updates have reintroduced it.  It would be nice to add a test to prevent this but I'm not sure the best way to test this. 
I'm happy to try adding a test if there are any suggestions on a good approach.  I'll also put more thought into it later and try to come up with something for discussion.
> Check if buffer's file is unrelated remote before checking it exists

- lisp/git-commit.el
Clicking the Co-authored-by entry in the Commit menu currently produces an error: `apply: Wrong type argument: commandp, git-commit-co-authored`.
This commit fixes that error by referring to the right function name.
Renaming the function would have made its name more consistent with other like functions, but it might have caused breakage? I couldn't find any use of the function on GitHub.
> Fix `git-commit-co-authored' typo in git-commit-mode-menu

- lisp/magit-diff.el
Add ignore-errors around face-attribute 'region :extend as mentioned in my comment on https://github.com/magit/magit/issues/3986#issuecomment-555391760
It caused byte-compiling errors on latest Emacs 27. Just slapped ignore-errors there as advised
by Henrik of doom-emacs at https://github.com/hlissner/doom-emacs/issues/2070
_I'm sending this pull-request - more as a convenience - not really sure if you would like to fix the problem exactly this way. But it fixed the issue I was experiencing._
> Fix face-attribute 'region :extend on Emacs 27

- lisp/magit-log.el
The `magit-keyword` face is currently applied to keywords in log messages greedily, e.g. the entire message `"[EMACS] Rebind C-]"` receives the `magit-keyword` face due to the trailing `]`.
- Make unused grouping construct shy.
- Avoid applying `magit-keyword-squash` face to whitespace.
- Hoist `magit-log-highlight-keywords` guard out of loop.
- Make keyword regexp non-greedy so as to handle cases like `"[EMACS] Rebind C-]"`.
- Avoid meaningless quoting of `?\]` inside regexp, as per advice in [`(elisp) Regexp Special`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html).  This is because backslash quoting does not remove special meaning of `?-` and `?\]` in regexps.
> magit-log-propertize-keywords: Fix regexp search

- Documentation/magit.org
- Documentation/magit.texi
Fixed a small typo in magit documentation.
#4015
> Fix small typo in magit.org

- lisp/git-commit.el
Hi!
This is a pretty minor itch: the way the
`git-commit-font-lock-keywords-*` variables are written right now,
square brackets cause comments to lose the comment face. From `make
emacs-Q`[^1]:
- `M-x magit-status RET`
- `c -e c`
- `# Write down some text RET`
- `# Add brackets around a [word] RET`
What I observe:
- the first line has the comment face,
- the second line has the default face,
- `[word]` has the keyword face.
What I expect:
- both lines have the comment face,
- … I can't tell whether it would make more sense to highlight
`[word]` or not.
This PR highlights the keyword.  My use-case is a commit.template file
containing comments with instructions about project-specific bracketed
keywords; it's actually nice that the keywords remain highlighted in
the comments.
Not …
> Fix git-commit fontification when comments contain brackets

- lisp/magit-log.el
This fix treats an empty list (or nil) `magit-log-remove-graph-args` as "never-match" so to never remove `--graph` in log commands.
Before this fix:
```lisp
;; Never remove `--graph`
(setq magit-log-remove-graph-args (list "something that will never match")) ;; Ugly
;; Remove `--graph` everywhere
(setq magit-log-remove-graph-args nil) ;; Confusing... (empty regex match everything)
```
Now:
```lisp
;; Never remove `--graph`
(setq magit-log-remove-graph-args nil)
;; Remove `--graph` everywhere
(setq magit-log-remove-graph-args (list "")) ;; empty string regex match everything
```
But, as a side note, **it doesn't mean users should actually do this**, because current switches like `-G` and `-- file` are broken due to literal `...` in git log output.
> Make empty magit-log-remove-graph-args never remove --graph

- lisp/magit-refs.el
The manual says that magit-show-refs (1) behaves as a refresh prefix
when called from a magit-refs-mode buffer, (2) respects
magit-prefix-use-buffer-arguments when called as a transient, and (3)
respects magit-direct-use-buffer-arguments otherwise.  The third part
is not the case.
Match the described behavior by updating magit-show-refs-arguments to
look at magit-direct-use-buffer-arguments unless the magit-show-refs
transient overrides the value with magit-prefix-use-buffer-arguments.
---
@tarsius I'm not sure if this is the best way to deal with this (particularly the change to the `magit-show-refs` transient).  If it isn't, please feel free to discard this and apply a cleaner fix.
> magit-show-refs: Match documented *-use-buffer-arguments behavior

- lisp/magit-patch.el
This PR was prompted by gh-4028.  It reorganizes the `magit-patch-create` transient a bit (in terms of levels, sections, and one binding change) and adds the following options: `--base`, `--interdiff`, `--range-diff`, `--rfc`, `--cover-from-description`, and `--notes`.
I've lazily decided not to add release notes because there's already a catch-all entry for the Transient switch that says "many popups gained new arguments and/or commands, most of which are not mentioned explicitly in these release notes".
I'd be interested to hear alternative suggestions for levels and bindings.
Closes #4028.
> Expand magit-patch-create transient

- Documentation/magit-section.org
- Documentation/magit-section.texi
- Documentation/magit.org
- Documentation/magit.texi
The variable `magit-log-section-args` is documented but no longer exists. See also #3879.
> Remove documentation of removed variable magit-log-section-args

- Documentation/magit-section.org
- Documentation/magit-section.texi
- Documentation/magit.org
- Documentation/magit.texi
Add documentation on using absolute `git` path in Darwin in `magit-git-executable`. Using the default results in a 20 times slowdown for some reason.
This was reported in #2982 and seems to have been confirmed by a few people [on reddit](https://www.reddit.com/r/emacs/comments/ffwxc9/performance_problem_with_magit_on_macos/).
Let me know if I should change or reword anything.
> Add documentation on using absolute git path in Catalina

- lisp/magit-git.el
_Optional_ was misspelled which causes the function _magit-inside-gitdir-p_ to not work.
> Optional was misspelled.

- lisp/magit-process.el
Fixes <https://github.com/magit/magit/issues/4076>.
When using Magit on a remote Git repository via TRAMP (using SSH), the
gpg-agent of the remote may prompt for a password.  Pinentry displays
the prompt through the terminal of the remote process, which until now
was not being handled by magit-process.
* lisp/magit-process.el (magit-process-password-prompt-regexps): Add
regexps to match the GnuPG prompts when requesting a password for a PGP
or SSH key through pinentry.
> magit-process: Add prompt regexps for GnuPG.

- Documentation/magit.org
- Documentation/magit.texi
Update the description of the option's default behaviour in accordance with PR #2520.
Note that `magit.texi` will require regenerating if this is merged.
> magit-clone-set-remote-head: Doc fix

- lisp/magit.el
The `magit-shell-command-topdir` and `magit-gitcommand-topdir` completion is now done in the context of the repository top level, which allows completing scripts and other files residing there.  Previously the completion was done from the context of the current `default-directory` which wasn't necessarily the repository top level making the completion of local files nonsensical.
> Improve the magit-{git,shell}-command-topdir completion

- Documentation/magit.org
- Documentation/magit.texi
The default value is `t`, but the manual claimed that it was `nil`.
> manual: Fix default value of magit-branch-read-upstream-first

- lisp/magit.el
See https://github.com/raxod502/straight.el/issues/520. Previously, when you made a shallow clone of Magit, then byte-compiling Magit would produce a warning `Cannot determine Magit's version`. This caused problems for users of the package manager `straight.el`, for example (see the linked issue). With the new code, Magit will not print this warning, and when `magit-version` is invoked, the commit hash will be reported. Behavior is only changed in the case that no tags are available in the repository, and none of the other version checks succeed.
> Make magit-version work properly in shallow clone

- lisp/magit-git.el
Simple fix for two typos. Hope it makes the text cleaner.
> Fix typo in comment on magit-git-executable

- lisp/magit-mode.el
The intention of `magit-display-buffer-same-window-except-diff-v1' is
to display diff buffers in a separate window. A nil action argument
passed to `display-buffer' is not always enough to accomplish this
when `display-buffer-base-action' has been customized, as in the
following example from section 28.13.4 of the Elisp
manual (Additional Options for Displaying Buffers):
(customize-set-variable
'display-buffer-base-action
'((display-buffer-reuse-window display-buffer-same-window
display-buffer-in-previous-window
display-buffer-use-some-window)))
For example, when used with
`magit-display-buffer-same-window-except-diff-v1', the above
customization will result in the diff buffer popping up in the same
window, and the commit message buffer not being displayed, when
`magit-commit-create' is …
> magit-display-buffer-same-window-except-diff-v1: inhibit-same-window

- lisp/magit-branch.el
Submodules can be completely up-to-date, yet still show as modified
because of a dirty worktree. Even if they weren't up-to-date, switching
branches with Git on the command-line ignores submodules, so we should
too. Otherwise this prevents the user from switching branches unless
they completely update and clean every submodule, which is unfriendly.
> magit-branch-checkout: Ignore submodule modifications

- lisp/magit.el
I am having the same problem as #4106 (my .emacs.d is also symlinked).
I believe `(magit-version)` fails due to the regexp for matching the version from the magit directory not being up-to-date. The regexp currently tries matching an 8-digit number, followed by a period, followed by any number of digits. I changed it to match a number, followed by more than one number or period, followed by a number.
If desired, I can make the regexp match the SemVer-scheme which it currently does not.
Due to symlinks being an issue in both regards, I initially suspected the usage of `file-chase-links` instead of `file-truename` to be the culprit. However, changing the method did not fix the problem.
Finally, I wonder if there is a better way to test changes than modifying …
> Fix regexp matching version from magit directory

- lisp/magit-section.el
As described in the docstring, the form for ‘eval’ is ‘(eval FORM)', and FORM
doesn’t need to be a symbol.
Without this, functions like ‘magit-insert-recent-commits' can’t be edebugged
if ‘magit-insert-section' is edebugged.
> Fix edebug spec for ‘magit-insert-section’.

- lisp/magit-utils.el
- lisp/magit.el
As promised, this implements the logic that I proposed in https://github.com/raxod502/straight.el/issues/520#issuecomment-633645316 to fix the problem where Magit would not be able to determine its version when installed via straight.el on Windows.
> Handle emulated symlinks created by straight.el

- lisp/magit-remote.el
It is possible for a repo to have no remote called "origin".  In this case, magit-remote-add fails when attempting to construct a suggestion for the to-be-added remote's URL.
Check that we have an "origin" remote URL before using it.
> magit-remote-add: Handle lack of "origin" remote

- lisp/magit-extras.el
Add some integration with project.el.  The `C-x p` map is the main way I navigate within and between projects nowadays, and so this is very nice to have.  It's modelled on the vc-dir integration which comes with project.el.  I also thought about somehow replacing vc-dir for git projects, but I think in the end it is more useful to have a separate key.
> Add project.el integration

- lisp/magit-extras.el
> magit-extras: Forward-declare project variables for byte-compiler

- lisp/magit-fetch.el
Add support for --unshallow.  Set this to level 7 in transient, since
this is a relatively uncommon command, and is the inverse of a shallow
clone which magit already has at level 7.
----
#
> magit-fetch: Add -u for --unshallow option

- lisp/git-commit.el
Fixes a small typo in the documentation of git-commit-keyword.
> Fix a typo in git-commit-keyword

- lisp/magit-merge.el
git merge -X <option> only uses a a single `-` according to https://git-scm.com/docs/git-merge
> git merge --X <option> -> git merge -X

- lisp/magit-blame.el
In Emacs 27.1, the `:extend t` face attribute needs to be applied in order
to extend it until the edge of the window, see Emacs' NEWS file.
See also 891ebdca where this was done for other faces.
IIUC it's not necessary to hide this behind a version check, since earlier versions of Emacs will simply ignore the unknown face attribute.
> Fix display of magit-blame's show-lines option for Emacs 27.1

- lisp/magit-status.el
Looks like a typo.  I think this fix saves a call to `(magit-git-version)` (and a consequent `git` process) for every single `magit-status` in a remote directory?
> Bug fix for `magit--tramp-asserts'

- lisp/magit-clone.el
* `lisp/magit-clone.el` (`magit-clone-internal`): Fix typo in `user-error` format string and pass it the expected format argument.
> magit-clone-internal: Fix user-error arguments

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-files.el
- lisp/magit.el
For the longest time we have tried hard to avoid doing this but
it is just not worth the effort and leads to an inferior result.
Now we add three bindings by default.
```elisp
;;;###autoload
(when magit-define-global-key-bindings
(let ((map (current-global-map)))
(define-key map (kbd "C-x g")   'magit-status)
(define-key map (kbd "C-x M-g") 'magit-dispatch)
(define-key map (kbd "C-c M-g") 'magit-file-dispatch)))
```
As you can see is easy to prevent these bindings from being added
and I hope having to do so won't upset anyone too much.  While we
did not add global bindings we already added these bindings in all
file-visiting buffers and we did not get any complaints about that.
This completely replaces `magit-file-mode` and the global variant,
which we define as an alias of the new …
> Add three global key bindings by default

- lisp/magit-process.el
A magit subprocess can prompt for input by a user with a prompt not matching a
prompt ending in `?` or `:`.
Example arc [phabricator](https://www.phacility.com/phabricator/) provided via [magit-arcanist](https://github.com/sideshowcoder/magit-arcanist):
```
Amend HEAD with lint patches? [Y/n]
```
This patch makes the ending in `?` or `:` optional.
> Match yes-or-no prompts not ending in ? or :

- Documentation/RelNotes/3.0.0.org
- lisp/git-rebase.el
This series updates `git-rebase-kill-line` to support killing lines selected with the region (as proposed in gh-4172).  It also adds region support to commands that operate on "commit" lines (`git-rebase-pick`, `git-rebase-reword`, `git-rebase-edit`, `git-rebase-squash`, and `git-rebase-fixup`).
---
@Stebalien @aesyondu Care to give this a try?
I'll plan to merge this in a few days if there are no objections.
> git-rebase: Region support for -kill-line and commit action commands

- lisp/magit.el
Had no manual defined before, so nothing lost, but it is more newbie
friendly to end after repetitive panic "?"-s in the manual.
At least it would have been a tiny bit easier for me.
> Show magit manual for magit-dispatch

- default.mk
Since Emacs 27.1 user-emacs-directory can also be in XDG_CONFIG_HOME or (~/.config).
> Check XDG convention for elpa dirs in default.mk

- lisp/magit-extras.el
+/- are not properly stripped from the last line in the active region due to no
trailing newline being in that region.
> magit-copy-section-value: Fix copying of last line

- lisp/git-commit.el
See #4279.
The result now looks like this:
> Add/Fix: (git-commit-mode) Highlighting of log headers

- Documentation/RelNotes/3.0.0.org
- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-bisect.el
- lisp/magit-log.el
I find alternate terms for bisecting very useful, and it's a common reason I resort to the command line.  I've tried to force the "good" and "bad" terms onto bisects a good number of times, and in most cases my brain isn't capable of keeping things straight.
This series adds support for parsing the status buffer when bisecting with alternate terms (second commit) and for running a bisect with alternate terms (third commit).
While I think more people than just myself will find this useful, I doubt most users will, given that I don't recall support for alternate terms being requested.  For this reason, I've put this functionality at a hidden level (6).
(The texi file hasn't been regenerated yet.)
> bisect: Support specifying alternate terms

- lisp/magit-process.el
Otherwise, on Windows an issue shows up with processes that output
CRLF-endings (e.g. python): the process-output is deleted due to the
subsequent code (which tries to improve output of counters).
---
On windows I encounter an issue that I don't see any output from processes (namely python), when executed via magit's "Run shell command". Python is supposed to output `\r\n` as line ending on windows (see e.g. https://bugs.python.org/issue13119).
I wrote a patch that fixes the issue, while still properly showing counting processes (which only output `\r` without `\n`, in order to erase the current line).
However, I'm not sure if this is the right place to fix the issue, or if it should be rather fixed outside magit (I have set `default-process-coding-system` to `(utf-8-dos . utf-8-unix)` if …
> magit-process: Respect process decoding user-setting

- Documentation/magit.org
- lisp/magit-mode.el
- lisp/magit.el
This changes the suggestion to set the hook only after magit is loaded.
Currently, copy-pasting from the manual leads to messages like 
`Symbol’s function definition is void: magit-after-save-refresh-status` when trying to
exit emacs and, even worse, strange debugger errors after files are saved.
I wasn't enough of an Emacs expert to know how hooks work, so this was unexpected
and annoying to me.
This commit replaces the suggested way to implement the hook with the answer from
https://emacs.stackexchange.com/questions/56309/auto-refresh-magit-status-only-when-magit-is-running.
==========
After making this, I saw that this doesn't quite fit the contribution guidelines in that I edited the file in Github and didn't add a feature branch. I hope that is OK for such a small change, but feel …
> Improve suggestion for magit after-save hook

- lisp/magit-gitignore.el
The magit-gitignore-in-subdir command fails when DIRECTORY is a remote dir. 
Use `file-local-name` to resolve it to a local name before giving it to git add.
> Only use local paths in magit-gitignore-in-subdir

- Documentation/magit.org
- Documentation/magit.texi
- lisp/magit-branch.el
When using submodules, having to switch the submodules manually after each (branch and) checkout operation is quite cumbersome, even with the nice "o u" keyboard shortcuts.
This PR adds the git option "--recurse-submodules" to the magit-branch (sub-) commands that checkout branches, visibility controlled by transient level.
> magit-branch/magit-checkout: add recurse-submodules option

- lisp/magit-files.el
As of 5a38e1bb0fffa0326a1b5073c0ce9b05386e5109, `magit-file-dispatch` forwards to `magit-dispatch` for dired buffers, which prevents using it to e.g. request a git log only for the currently visited directory.
I think this was an unintended change, but I'm not sure. On one hand, many of the `magit-file-dispatch` commands, such as blame, are not relevant to dired buffers. On the other hand, the description of 5a38e1bb0fffa0326a1b5073c0ce9b05386e5109 doesn't seem to mention this change at all.
> Fix magit-file-dispatch for dired buffers

- lisp/magit-log.el
I added an option to the log screen `-i` to be able to grep commit messages in a case insensitive way. The keyboard shortcut is `-i` (it was available). There's no documentation to update.
I tried combining the `-F` key to be both a transient-option and a transient-switch, but I think it's simpler as a toggle. 
Thank!
> log: search messages case insensitive

- lisp/magit-extras.el
The format of `project-switch-commands` changed.  The `car` is now the command, and its key binding is looked up in `project-prefix-map`:
> Remove the duplication from project-switch-commands's config
> 51698f77dd 2020-12-13 22:50:55 +0200
> https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=51698f77dd6356049fcacdb01ebe80cfe4c67272
This change is included in `project.el` version `0.5.4` of `2021-03-09`, which also lowers the minimum required Emacs version from `26.3` to `26.1`: https://elpa.gnu.org/packages/project.html
Consistently calling `magit-project-status` instead of `magit-status` has the benefit of going through [`project-remember-project`](http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/project.el#n1201), which marks the selected project as the most recently …
> magit-extras: Update project.el integration

- lisp/magit-extras.el
Problem: Magit messes with my `project-switch-commands`.
The variable `project-switch-commands` is customizable, and I configure it to contain the commands I want. Since I use `use-package` to load `magit`, `project-switch-commands` may be set before either `magit` or `magit-extras` is loaded. 
However, once `magit-extras` is loaded it unconditionally modifies `project-switch-commands`. This is not ideal.
This PR only adds the "Magit" command if the variable hasn't been customized. If also ensures that the "Magit" command is added _after_ the default ones, which is a better default in my opinion.
> magit-extras: Do not modify customized project-switch-commands

- t/magit-tests.el
This change ensures symlinks in the base test directory for toplevel tests are expanded within the `magit-with-test-directory` macro. Doing this ensures that the fully expanded paths returned from `magit-toplevel` will match expanded relative paths (e.g., `(expand-file-name "repo/")`).
This issue was found on macOS (11.2.2) where temp files/directories are created under `/var/...` which is symlinked to `/private/var/...`.
> Expand symlinks in top-level test directory

- lisp/magit-bookmark.el
Currently there is an issue in both **creating** and **visiting** bookmarks for Magit buffers while using the Bookmark+ package. Upon investigation, a quick fix can be made that's compatible with both vanilla bookmarks and Bookmark+.
- Manually creating alist instead of using the (bookmark+ based)`bookmark-prop-set` function, which expects
the bookmark to have the structure `(bookmark-name . alist)`, which is not ready yet at the time of that call.
- Explicitly calling bookmark+ jumping function. In bookmark+, custom handlers are expected to handle
the buffer jumping.
After this PR was created, a patch was made to the bookmark+ package that solves the first issue. The original PR was composed of 2 fixes to the `magit-bookmark` file. I then forced pushed in order to have only the 2nd fix …
> bookmark: mending incompatibilities with bookmark+ package

- lisp/magit-clone.el
- lisp/magit-git.el
- lisp/magit-push.el
I am currently running a poll and early results indicate that I was wrong in assuming that the vast majority name the upstream (primary, original, official ...) remote "origin".  Many users call their own fork "origin" and it seems we can quite easily accommodate them.
I'll probably say more about this once the results are in but until then we can just silently make their lives a bit better.
> Support naming the primary (upstream) remote something other than "origin"

- .github/workflows/test.yml
- Makefile
- t/default.nix
- t/magit-tests.el
- Add simple tests for `magit-bare-repo-p`, which is implemented with both Git and libgit.
- Install Emacs with libegit in CI via a custom Nix install.
- Run tests using both Git and libgit functions in CI by adding a `git_impl` dimension to the build matrix.
> Run tests using both Git and libgit implementations in CI

- .github/workflows/test.yml
Merges the "Test with libgit" and "Test with git" CI steps into a singular "Test" step that uses string substitution to select the `make` target.
There should be no functional change here other than removing one disabled step for every test in the Actions interface.
> Consolidate git/libgit CI steps

- lisp/magit-log.el
magit--maybe-update-revision-buffer sets up an idle timer function
that captures the result of calling magit-show-commit--arguments.
Before the call, the revision buffer is set as the current buffer.
Changing to the revision buffer interferes with toggling the file
restriction from the log buffer via magit-diff-toggle-file-filter.
The filter can be turned off, but, if the caller moves to another
line, the filter can't be turned back on again because, in order to
find the file arguments, magit-show-commit--arguments needs to be
called from the log buffer.
Call magit-show-commit--arguments without changing the buffer so that
the file arguments can still be grabbed from the magit-log-mode
buffer.  This shouldn't change the behavior in any other way because
underneath magit-diff-arguments …
> magit--maybe-update-revision-buffer: Honor log's file filter

- lisp/magit-process.el
fixes #4393
- Add a newline to the option user entered, so that it gets submitted to git prompt.
- Insert the option in the process buffer, so user sees what option was chosen. Also newline puts the next git message on a newline.
I tried using `magit-process-kill-on-abort`, so the git process gets killed when user cancels with `C-g`. But was unsuccessful. Canceling any of `Option` or `Token` prompts, do not kill the git process.
> Fix git credential manager core by adding a newline to the chosen option

- lisp/magit-utils.el
(To be applied to the crm branch.)
In `magit-completing-read-multiple*`, this avoids changing the return value of
`split-string`. With this, selectrum's crm function works correctly instead of
signaling an error.
(The first commit doesn't change behaviour, only formatting, to make the second
commit easier.)
> [crm] Override split-string more safely

- Documentation/RelNotes/3.1.0.org
- lisp/magit-log.el
Unless I'm missing something, this is a rather trivial fix.
Since `magit-log-select-quit-function` is a buffer-local variable, killing the buffer then calling the function means that nothing is ever called. The quit function should be temporarily bound so it isn't lost.
> Fix magit-log-select-quit: actually call quit func

- lisp/magit-push.el
The branches and remote names are passed unescaped to `magit-confirm` from
`magit-push-current-to-{upstream,pushremote}`.  `magit-confirm` uses its
prompt as a format, which may cause an "Invalid format operation error" when
a branch or remote name contains a "%" character.
--
Magit 3.1.1, Git 2.32.0, Emacs 27.2, darwin
To reproduce on magit-push-current-to-upstream:
1. create branch: `b s` `test%branch`
2. try to push branch, creating upstream one: `P -n u` `origin/test%branch`
Similarly for magit-push-current-to-pushremote:
1. create remote: `M a` `test%remote` `https://localhost/` `n`
2. try to push branch, setting its pushremote: `P -n p` `test%remote`
Backtrace (`magit-push-current-to-upstream`):
```
Debugger entered--Lisp error: (error "Invalid format operation %b")
format("Really …
```
> magit-push-current-to-{upstream,pushremote}: Escape remote and branch names

- lisp/magit-blame.el
Passing the --first-parent option to git-blame(1) will make git only
follow the first parent commit upon seeing a merge commit. This option
can be used to determine when a line was introduced to a particular
integration branch, rather than when it was introduced to the history
overall.
> magit-blame: Add --first-parent

- lisp/magit-diff.el
This is a follow-up to the discussion in <https://github.com/magit/magit/commit/d477163d34a22ff7a30597d0fbc70f62355bceff#commitcomment-53563206>.  The second commit has the main fix.
Below are some cases I considered while working on this.
<details>
<summary>test cases</summary>
Cases tests with master (877f7140) and this PR.
---
```sh
cd $(mktemp --tmpdir -d magit-XXXXX)
fname='foo bar'
git init
echo a >"$fname"
git add "$fname"
```
master: has rename marker with nonsense file name
pr: expected
---
```sh
cd $(mktemp --tmpdir -d magit-XXXXX)
fname='foo bar'
git init
echo a >"$fname"
git add "$fname"
git commit -m'c1'
git rm "$fname"
```
master: has rename marker with nonsense file name
pr: expected
---
```sh
cd $(mktemp --tmpdir -d magit-XXXXX)
fname='foo β'
git init
echo a >"$fname"
git …
```
> magit-diff-wash-diff: Fix handling of file names with spaces

- lisp/magit-repos.el
This PR is a complement of the commit 7f666751c0226f37a65f3e9d7dba4c02aa3c252f to be able to reverse the sort order.
For exemple : to have repositories with the most local changes unpushed to upstream at the top of the list, you need to set `magit-repolist-sort-column` to "B>U" and reverse the result. But there is no option to do the reverse.
The implementation is very simple: it just change the cdr of the `tabulated-list-sort-key` variable. According to the documentation of this variable, that's the way to reverse the sort order.
> magit-repolist-sort-reverse: New option

- lisp/magit-status.el
Hi,
This is a tiny PR, which only ensures that in `magit-status`, separating spaces are not part of font-locked texts. Thus, themes altering the background color does not make the formatting spill outside of the formatted text _per se_.
Example here (https://imgur.com/a/zoB9Z2i) with doom-flatwhite – the space between `sample.git` and `remote [...]` shouldn't be font-locked in red background.
> Ensure that whitespaces are not decorated

- Documentation/magit-section.org
- Documentation/magit-section.texi
Just a small documentation fix.
> doc: classify `magit-insert-section` as a macro

- lisp/magit.el
Empty result from function `magit-version` when magit is distributed with `*.elc` and `*.el.gz` without `*.el`.
This PR try to make `magit-version` work with this situation.
> magit-version: more flexible for magit.el not exists (magit.el.gz and magit.elc exists)

- lisp/magit-wip.el
```
When magit-wip-commit-worktree receives a non-nil FILES argument, it
feeds the result to update-index.  If triggered by operating on items
in the untracked section, FILES may contain directories.  In this
case, the update-index call ignores directories but succeeds:
$ git status -s
?? d/
?? f1
$ git update-index --add -- f1 d/
Ignoring path d/
$ git status -s
A  f1
?? d/
Ignoring directories seems acceptable because 1) when staging with the
composite wip modes, directory files are subsequently captured by the
post-stage magit-wip-commit-index call and 2) the documentation
explicitly says untracked files are not covered by wip modes (which is
particularly relevant when discarding untracked changes).
However, as of Git v2.32.0, specifically 6e773527b6 (sparse-index:
convert from full to …
```
> magit-wip-commit-worktree: Filter out directories

- lisp/magit-git.el
For tramp in Windows, expanding the file name first before to get the local
name. Otherwise "c:" will be added to the filename.
For example, "/plink:user@host:~/R/" should be converted as
"/home/R/" and not "c:/home/R/"
Signed-off-by: Shuguang Sun <shuguang79@qq.com>
> fix filename converter for tramp in Windows

- lisp/magit-bisect.el
- lisp/magit-git.el
- lisp/magit-utils.el
- lisp/magit.el
Use with-connection-local-variables macro to make sure that
`shell-file-name` and `shell-command-switch` have values appropriate
for the machine we are trying to run the command on.
Consider the scenario where we are using Emacs + Magit running on a
Windows machine while manipulating a remote repo on a Linux machine
with Tramp + plink. Without `with-connection-local-variables` we'll
have `shell-file-name` pointing to `cmdproxy.exe` which, for obvious
reasons, won't work on the remote Linux box.
> magit--shell-command: Use with-connection-local-variables macro

- lisp/magit-git.el
This allows people who named their branch `head` to still see them.
Fix #4575
> magit-list-refs: exclude case-sensitive HEAD from branch list

- default.mk
- docs/RelNotes/3.4.0.org
- docs/magit.org
- docs/magit.texi
- lisp/Makefile
- lisp/magit-clone.el
- lisp/magit-git.el
- lisp/magit-mode.el
- lisp/magit-sparse-checkout.el
- lisp/magit.el
Commits 1-5 add support for `git sparse-checkout`.  The second commit is the main addition, and its commit message has some background on sparse checkouts and explains which aspects the new magit-sparse-checkout.el library targets.
Commit 6 adds partial clone support by adding `--filter` to `magit-clone`.  Although they can work together, partial clones aren't inherently coupled to sparse checkouts, but I decided to include the last commit given that both features share the same issue (gh-4102).
Closes #4102.
cc @aseltmann
---
I'm marking this as a draft, mostly because I've run out of time to read this over tonight (apologies for bad typos or half-thoughts that may have slipped through).  I think it's likely that I won't get back to this until next weekend, but I'd of course be happy for …
> Sparse checkout and partial clone support

- lisp/magit-bisect.el
- lisp/magit-blame.el
- lisp/magit-diff.el
- lisp/magit-extras.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit.el
This series fixes spots in the code base that are incompatible with Git's recent and experimental SHA-256 support (basically anywhere that hard codes the expectaion of 40-character object names).
I found these spots with two checks:
```
$ git grep '\b40\b'
$ git grep -E '[a-f0-9]{40}'
```
I expected that the empty tree hash might pop up somewhere in there, but `magit-headish` already handles this in a nicely compatible way.
Fixes #4516.
> Updates for compatibility with SHA-256 repositories

- lisp/magit.el
In response to #4572.
@kyleam what do you think?
Additionally (but optionally) adding all alphabetic bindings would
look like this:
``` diff
diff --git a/lisp/magit.el b/lisp/magit.el
index d83ccbb90..19cbd3d30 100644
--- a/lisp/magit.el
+++ b/lisp/magit.el
@@ -373,7 +373,15 @@ (transient-define-prefix magit-dispatch ()
("<tab>" "   toggle section at point"  magit-section-toggle)
("<return>" "visit thing at point"     magit-visit-thing)]
[("C-x m"    "show all key bindings"    describe-mode)
-    ("C-x i"    "show Info manual"         magit-info)]])
+    ("C-x i"    "show Info manual"         magit-info)]]
+  ["Other commands"
+   :level 7
+   ("G" "Refresh repository buffers" magit-refresh-all)
+   ("K" "Untrack file"               magit-file-untrack)
+   ("n" "Goto next section" …
```
> Make magit-dispatch slightly more discoverable

- lisp/magit-status.el
I use `magit-status-show-hashes-in-headers`, and noticed that the order of hash and commit summary is not consistent in the header, the push header has the wrong order. This PR fixes this.
> Fix hash/commit summary order in push branch header

- lisp/magit-autorevert.el
If we are not going to do anything because auto-revert-mode or global-auto-revert-mode are on, don't call executable-find, file-readable-p or magit-toplevel.  This is particular important for remote files, for which calling those functions is expensive.
> magit-turn-on-auto-revert-mode-if-desired: do cheaper checks first

- lisp/magit-log.el
A call to magit-log-get-commit-limit can return nil, so make sure we don't try
to compare nil to a number. I ran into this when running `magit-status` in a repository because of a call to the `magit-log-insert-child-count` function where we compare the result of calling `magit-log-get-commit-limit` with `=`. It seems to be the case that if `magit-buffer-log-args` is `nil`, then the result of the whole call to `magit-log-get-commit-limit` will also be `nil` and so a call of the form `(= <num> nil)` will cause a failure.
> Use eq instead of = in magit-log-insert-child-count

- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-mode.el
- lisp/magit-status.el
- lisp/magit-utils.el
- lisp/magit-wip.el
- lisp/magit.el
This is response to #4065 but doesn't go as far as the changes @phil-s linked to in that issue.
I have come to the conclusion that it is not necessary to try to catch the very first call to `git` that a user invokes on a new host using Magit (even if `magit-status` wasn't responsible for that), because I cannot remember the last time that would have been useful and because I did not like the introduction of `magit-process-file-git`.  However if we later decide otherwise, we could simply add that function and add a call to `magit-git-version-assert` there.
The central idea is that callers `magit-git-version<` and `magit-git-version>` do not have to worry about caching and error reporting because these functions use `magit-git-version`, which takes care of all that.  They obviously should …
> Refactor Git version asserts

- lisp/magit-blame.el
fix #4619, see there for more detailed discussion
In brief, `magit-blame--make-highlight-overlay` should add an overlay from `beg`
to end-of-line that contains `beg`. Previously, however, it was from `beg` to
end-of-line that contained point, but this should fix that.
Wrapping things in `save-excursion` and `save-restriction` is probably overkill
since `magit-blame--make-highlight-overlay` is currently only called from
`magit-blame--make-overlays` where it is already warpped in `save-excursion` and
`save-restriction`, but it's included to be extra cautious.
> apply blame highlight-overlay to just one line

- lisp/magit.el
> Don’t try to evaluate startup assertions when byte-compiling.

- lisp/magit-sequence.el
Got Forge on the mind? 😉 
Small fixup to 73b44644f6ce632990c86430aa281a5e817d0bb2. Did a quick grep and this appears to be the only such typo.
> Fix forge/force typo

- docs/magit-section.org
- docs/magit-section.texi
- docs/magit.org
- docs/magit.texi
- lisp/magit-base.el
- lisp/magit-bisect.el
- lisp/magit-diff.el
- lisp/magit-git.el
- lisp/magit-log.el
- lisp/magit-merge.el
- lisp/magit-mode.el
- lisp/magit-pkg.el
- lisp/magit-refs.el
- lisp/magit-section.el
- lisp/magit-stash.el
- lisp/magit-status.el
- lisp/magit-submodule.el
- lisp/magit-worktree.el
- lisp/magit.el
Get out the cheese!
It took a while (see #2554) but you can now use the mouse to perform many actions:
- Double click (mouse-1 or mouse-2) a section heading to expand or collapse it.
- Single click in the left fringe to expand or collapse the appropriate section.
- Right click (mouse-3) to show a context menu, with common as well as
section-specific commands.
- If you are using Emacs 28 or greater you have to enable `context-menu-mode`
for this to work.
- For older Emacsen set `magit-section-show-context-menu-for-emacs<28` to `t`
before loading `magit-section`.
- Magit's menu-bar menu now features all transient commands and most others
as well.
- This menu is also available from the context-menu.
- By default "popup navigation" is now enabled in Transient popups, including
mouse support. …
> Support mousing

- lisp/magit-stash.el
External diff tools may cause git to produce errors like "unrecognized
input" when the output is fed back into `git apply`.  Pass
`--no-ext-diff` to `git diff` where necessary in magit-stash.el.
> magit-stash: Disable external diff tools

- lisp/magit-diff.el
- lisp/magit-git.el
Git supports revisions that match a commit message:
:/<text>, e.g. :/fix nasty bug
A colon, followed by a slash, followed by a text, names a commit whose commit message matches the specified regular expression. This name returns the
youngest matching commit which is reachable from any ref, including HEAD. The regular expression can match any part of the commit message. To match
messages starting with a string, one can use e.g.  :/^foo. The special sequence :/! is reserved for modifiers to what is matched.  :/!-foo performs a
negative match, while :/!!foo matches a literal ! character, followed by foo. Any other sequence beginning with :/! is reserved for now. Depending on
the given text, the shell’s word splitting rules might require additional quoting.
However, Magit would not support …
> Support revisions that match commit message

- lisp/magit-refs.el
I noticed that `magit-visit-ref-behavior` was no longer respected in the Magit Refs buffer, and I narrowed down the issue to this part of the code (`magit-visit-ref`) not working according to its intended behavior (in fact, it was behaving the opposite of the documentation afaiu):
``` 
When invoked from a menu this command always behaves like `magit-show-commit'.
``` 
This solves the issue I had with `magit-visit-ref-behavior` not being respected and should actually implement the documented / intended behavior of the function.
> Fix behaviour of magit-visit-ref outside of magit menus

- lisp/magit-files.el
Calling `magit-find-file` in a rust lsp environment causes `#'lsp` to be
called again with the contents of the older file instead.
This commit seems to resolve it, but I'm not sure if I also have to wrap
the let-bind to prevent buffer hooks from being called.
See linked issue[1] for more information and a lengthier discussion
[1] https://github.com/doomemacs/doomemacs/pull/6309
> Resolve magit-find-file calling hooks

- docs/magit.org
- docs/magit.texi
- lisp/magit-diff.el
Two minor doc updates:
* Typo in docstring for `magit-diff-buffer-file`.
* Update for the keybindings used to cycle through previous arguments in a transient (`transient-history-prev` and `transient-history-next`).
> Small doc updates

- lisp/magit-mode.el
Hi Jonas,
```
From etc/NEWS in emacs.git:
*** 'list-bookmarks' now includes a type column.
Types are registered via a 'bookmark-handler-type' symbol property on
the jumping function.
```
This adds support for it to Magit.
> Support bookmark-handler-type for Magit bookmarks

- docs/RelNotes/3.3.0.org
- lisp/magit-log.el
By setting magit-log-merged-commit-count.
> Make magit-log-merged's number of shown commits configurable

- lisp/magit-push.el
The previous implementation was basically wrong because it didn't
handle push.default or resolve the remotes and refspecs separately
like git push actually does.
An easy example is if you have a branch `fork` tracking `fork/master`, the previous implementation said it would push to `fork/master` even though the default `push.default` value `simple` means it would push to `fork/fork`.
> magit-push: Fix magit-push-implicitly--desc

- docs/magit.org
- docs/magit.texi
I noticed today that following the link in the manual to https://emacsair.me/2016/01/18/magit-2.4/ brought up a 404.  Initially I thought to replace it with an Archive.org link, https://web.archive.org/web/20210618023341/https://emacsair.me/2016/01/18/magit-2.4/ , but then when I looked at the `git blame` for that line in the manual I saw it had a bit of a storied history, bouncing back and forth between `.../2016/01/17/...` and `/2016/01/18/...`:
| Commit | Date | Link target |
|---|---|---|
| 41764f9aa0fb6689388cbfdf89b61efb60e10d8f | `2016-01-18 00:05:00 +0100` | `.../2016/01/17/...` |
| 2e757a8c919b53edddb186e36e055e011e3b0ab3 | `2016-01-18 00:09:00 +0100` | `.../2016/01/18/...` |
| 0640097d237fd3cebfc51da107a8c7924bba7421 | `2016-11-24 13:00:58 +0100` | `.../2016/01/18/...` |
| …
> manual: re-update link to 2.4 release blog post

- docs/RelNotes/3.4.0.org
- docs/magit.org
- docs/magit.texi
- lisp/magit-clone.el
- test/magit-tests.el
This patch permits `magit-clone-url-format` to be represented as an alist mapping hostnames to URL formats. This way Magit can be configured to translate repository names into URLs when using servers that employ different URL schemes. The current value type (string) is kept for backwards compatibility.
Example usage with sr.ht:
``` 1c-enterprise
ELISP> (add-to-list 'magit-clone-name-alist '("\\`\\(?:sourcehut:\\|sh:\\)\\([^:]+\\)\\'" "git.sr.ht" "sourcehut.user"))
(("\\`\\(?:sourcehut:\\|sh:\\)\\([^:]+\\)\\'" "git.sr.ht" "sourcehut.user")
("\\`\\(?:github:\\|gh:\\)?\\([^:]+\\)\\'" "github.com" "github.user")
("\\`\\(?:gitlab:\\|gl:\\)\\([^:]+\\)\\'" "gitlab.com" "gitlab.user"))
ELISP> (setq magit-clone-url-format '(("git.sr.ht" . "git@%h:~%n") (nil . "git@%h:%n.git")))
(("git.sr.ht" . …
```
> Allow magit-clone-url-format to be more dynamic

- docs/magit.org
- docs/magit.texi
- lisp/magit-clone.el
- test/magit-tests.el
The patch adds a new item to the default value of `magit-clone-name-alist` so Magit knows about Sourcehut. The default value of `magit-clone-url-format` has to be also changed to accommodate the URL scheme used by Sourcehut which differs from the ones provided by Github and Gitlab.
See #4738 for more details/discussion.
Before the patch:
``` emacs-lisp
ELISP> (magit-clone--name-to-url "sh:nbarrientos/dotfiles")
*** Eval error ***  Not an url and no matching entry in ‘magit-clone-name-alist’
```
After the patch:
``` emacs-lisp
ELISP> (magit-clone--name-to-url "sh:nbarrientos/dotfiles")
"git@git.sr.ht:~nbarrientos/dotfiles"
ELISP> (magit-clone--name-to-url "sourcehut:pkal/compat")
"git@git.sr.ht:~pkal/compat"
```
In other words, invocations like:
```
M-x magit-clone u …
```
> Enable cloning repositories in Sourcehut by name

- lisp/magit-diff.el
Currently Magit can only identify renames in diffstats like:
```
file1 => file2
dir1/dir2/{file1 => file2}
dir1/{dir2/file1 => dir3/file2}
```
This patch allows discovering directory renames like:
```
dir1/{dir2 => dir3}/file1
{dir1 => dir2}/file1
```
by handling any construct `{A => B}` as a replacement rule and simply applying it.
This change improves the user experience when using `magit-jump-to-diffstat-or-diff`.
> Improve file renames identification

- lisp/git-rebase.el
Previously, the rebase todo list would have the top half of the key bindings font-locked but the bottom half would be single-quoted, e.g. \'c'.
This pull request fontifies all keybindings for uniformity (and visual prettiness).
-------
> git-rebase-mode-show-keybindings: font-lock single-quoted keys

- lisp/magit-commit.el
- lisp/magit-diff.el
Technically `(t)` and `t` are equally valid non-`nil` values for the `inhibit-same-window` display buffer action alist entry, but to minimize confusion and proliferation of future mistakes, use the simpler and more widespread boolean.
> Fix display buffer action alist syntax

- docs/magit.org
- docs/magit.texi
Fixed a typo: `rational` -> `rationale`.
I've tried updating the manual and attached its output, but that also changed the `magit.texi` in two other places. Those changes look odd to me. One adds (or removes?) a newline at EOF, the other mangles an s-expression's indentation. So of course just tell me and I'll just drop that part of the commit!
> manual: fix a typo

- lisp/git-commit.el
This is a commonly used header, for example in patches for the Linux kernel (see
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst).
> git-commit: Add "Co-developed-by" header

- docs/magit.org
- docs/magit.texi
I have been suffering degraded magit performance on macOS for a long time. This [superuser question](https://superuser.com/questions/1452865/git-is-working-painfully-slow) finally gave me the hint to check the performance of the two executables and turns out the native mac `git` is indeed much faster than the one I had installed using `nix`. This resulted in much faster response times from `magit`.
This PR updates the "MacOS Performance" section of the docs to note this
> Docs - performance notes on macOS

- lisp/magit-extras.el
Hello @tarsius,
I want to start a discussion about reasonable limitations of the Compat package. When I went over the Compat code base, I found one function which I think stands a bit out. This is the function `dired-get-marked-files`, which I think should not be part of Compat. I think reasonable limitations for Compat are the following:
- No advices and no overrides to avoid jeopardizing Emacs stability.
- No interactive commands to not change the user interface.
- No modes, since they are usually user facing.
- No functionality which is impossible to backport obviously, e.g., bigint support.
- No functionality which will be too slow and will result in performance bugs, e.g., `string-pixel-width` cannot be backported with sufficient performance from my current understanding.
- No …
> Revert "Use compat-dired-marked-files"

- docs/magit.org
- docs/magit.texi
- lisp/magit-clone.el
I vaguely remember somebody trying to add something like this to Magit in the past but not sure it has been proposed in this context. My apologies in advance if this has been already deemed not necessary.
I need to run code after a new repository is cloned, but only after the Git process has successfully finished. What I want to do is to add the repository to the project's database. 
Before, I was doing something like this:
```lisp
(defun my/magit-maybe-remember-project (repository directory args)
(when (file-directory-p directory)
(project-remember-project (cons 'vc directory))))
(advice-add 'magit-clone-internal :after #'my/magit-maybe-remember-project)
```
However this is not good enough as there's a race condition between Git finishing (async process) and my code being executed. It …
> Add hook `magit-after-successful-clone-hook'

- lisp/magit-diff.el
When viewing the log and using `SPC` (`magit-diff-show-or-scroll-up`) to view commits in another window, the `(window-width)` obtained by the following code is the *selected* (log) window, which may be quite narrow due to margin usage for log buffers.  This can cause the summary line in the resulting commit buffer to be wrapped at a smaller number of characters than was specified, even though the revision buffer's window is sufficiently wide.
```el
(defun magit-insert-revision-message ()
...
(when magit-revision-fill-summary-line
(let ((fill-column (min magit-revision-fill-summary-line
(window-width))))
(fill-region (point) (line-end-position))))
```
This PR changes that to `(window-width (get-buffer-window nil t))` to find a window for the current buffer (which is the revision buffer). …
> magit-revision-fill-summary-line: Use revision buffer's window width

- docs/magit.org
- docs/magit.texi
- lisp/magit-extras.el
I was reading about `magit-diff-edit-hunk-commit` when I saw a comment about `magit-rebase-edit-command`, mentioned there once. I've struggled finding further information, until I realized there is command with a very similar name, `magit-rebase-edit-commit`. I might be wrong, but I assume this should be the right name to mention.
I updated the 2 files where this command is mentioned, keeping `magit.texi` unchanged.
> magit-rebase-edit-command -> magit-rebase-edit-commit

- docs/magit.org
- docs/magit.texi
The margin toggle command was documented as `L t` but the transient menu shows `L L`: https://github.com/magit/magit/blob/main/lisp/magit-log.el#L520
> Documentation: correct magit-toggle-margin key binding

- lisp/magit-base.el
- lisp/magit-log.el
- lisp/magit-process.el
- test/magit-tests.el
This patch centralises the generation of ellipses by extending the functionality provided by `magit-ellipsis`, allowing end users to customise for instance the ellipsis used in `magit-log` buffers.
See [discussions/4907](https://github.com/magit/magit/discussions/4907) for more background and extra information.
> magit-base: consolidate ellipsis customisation

- docs/magit.org
- docs/magit.texi
Changed all remaining http:// Urls in magit.org documentation to https:// .
Each Url that was changed was checked before changing to ensure an https:// Url actually exists.
The motivation for this was the http:// Url used for the package source (http://melpa.org/packages); of all the links, that is probably the most important one in terms of security.
> Switch Urls from Http to Https

- docs/magit.org
- docs/magit.texi
git-commit-fill-column was deprecated in Magit 2.9.0. It should be removed from the manual to avoid confusion since the variable is no longer present in the codebase.
Link: https://github.com/magit/magit/commit/a277432e806af89c3bdd6046721c4db948443120
Link: https://github.com/magit/magit/issues/3067
> manual: Remove references to git-commit-fill-column

- docs/magit.org
- docs/magit.texi
Played with the _magit-list-repositories_ and encountered two differences between implementation and the manual.
Updated the manual regarding _magit-repository-directories-depth_ and _magit-repolist-column-flags_ to the best of my knowledge.
> manual: update chapter Repository List

- docs/magit.org
While installing magit manually I noticed that the manual left out that the library compat is also required. I also corrected the with-editor path.
> manual: compat is also a required library

- lisp/magit-clone.el
Fixes a bug in `magit-clone-internal` where the function would mistakenly ignore the `--origin` value from args
> magit-clone-internal: correctly get origin value from args

- .mailmap
- docs/magit.org
- docs/magit.texi
- lisp/magit-repos.el
- lisp/magit-submodule.el
The words "appropriate" and "unspecified" were misspelled in the docstrings for `magit-repolist-columns` and `magit-submodule-list-columns`, as well as their entries in the manual.
I've also aliased my ancient email account in `.mailmap`, although I wasn't sure what the protocol was for updating that.  It only appeared in one pre-1.2.0 commit.
> Correct "appropriat" and "unspecifed" misspellings

- lisp/magit-apply.el
Prompts have `: ` at the end by convention; when missing, there is no space between the prompt and the minibuffer input, which is ugly.
> magit-unstage-file: Add missing colon to prompt

- lisp/magit-core.el
The context of this patch is that the app-emacs/magit package in Gentoo Linux no longer requires app-emacs/libegit2 as a dependency; see downstream bug: https://bugs.gentoo.org/910381
However, without libegit2, magit-libgit.el can neither be byte-compiled nor loaded (because it requires libgit). Therefore the Gentoo package in its default configuration no longer installs magit-libgit.
Unfortunately, this leads to a warning message when the libegit2 module is present (for unrelated reasons) on the user's system:
```
Error while loading ‘magit-libgit’: (file-missing "Cannot open load file" "No such file or directory" "magit-libgit")
That is not fatal.  The ‘libegit2’ module just won’t be used.
```
This patch suppresses that warning message by testing `magit-inhibit-libgit` before trying to …
> Don't try to load magit-libgit when magit-inhibit-libgit is set

- lisp/magit-git.el
- lisp/magit-stash.el
Fixes a type error preventing stashes being popped from https://github.com/magit/magit/commit/f6f4b96b641a5af75e90b5431a32369ab0f664a7. 
Since `stash` is a string, there's no need for to `apply` `magit-git-items`, it can be called directly.
EDITED: (Also fixes an issue with stashes not being popped, see comment below).
Backtrace of the error this fixes:
```
Debugger entered--Lisp error: (wrong-type-argument listp "stash@{0}")
apply(magit-git-items "stash" "show" "-z" "--name-only" "stash@{0}")
magit-stashed-files("stash@{0}")
(apply #'magit-anything-staged-p nil (magit-stashed-files stash))
(not (apply #'magit-anything-staged-p nil (magit-stashed-files stash)))
(and (not (apply #'magit-anything-staged-p nil (magit-stashed-files stash))) "--index")
(magit-run-git "stash" "apply" stash (and …
```
> magit-stashed-files: Use magit-git-items directly without apply

- lisp/magit-extras.el
- lisp/magit-log.el
- lisp/magit-notes.el
- lisp/magit-process.el
- lisp/magit-remote.el
- lisp/magit-sequence.el
- lisp/magit-tag.el
- lisp/magit.el
Cc: @kyleam
1. `M-x emacs-version RET`
```
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2023-08-10
```
2. Install GNU ELPA package [`relint`](https://elpa.gnu.org/packages/relint.html)
3. `M-x relint-directory RET path/to/magit RET`
```
Relint results for /home/blc/.emacs.d/src/magit/
lisp/magit-extras.el:733:39: In call to skip-syntax-backward: Invalid char `s' in syntax string (pos 1)
">s-"
.^
lisp/magit-extras.el:783:41: In call to replace-regexp-in-string: Duplicated `\' inside character alternative (pos 5)
"^[ \\+\\-]"
......^
lisp/magit-log.el:1269:23: In magit-log-reflog-re: Optional expression matching an empty string (pos 127)
"^\\(?1:[^\000\n]+\\)\000\\(?5:[^\000\n]*\\)\000\\(?:\\(?:[^@\n]+@{\\(?6:[^}\n]+\\)}\000\\(?10:me …
```
> Address XR/Relint regexp/syntax linter warnings

- lisp/git-commit.el
The filename added to `auto-mode-alist` must be adjusted to account for tramp and versions because that is how the `auto-mode-alist` matching is done.
This code is based on [these](https://github.com/emacs-mirror/emacs/blob/647bcec4f537d49b7a1e6d200ec787fec11ed81a/lisp/files.el#L3315-L3324) lines.
This fixes #4987
I tested this change on my desktop which has a tramp connection to files that I am working on.  Before the change, the commit message buffer opened as fundamental mode, but only only remote ssh files with tramp.  After the change, both the local files and the remote ones are honoring the `git-commit-major-mode`.
> git-commit-setup: Fix auto-mode-alist for remote files

- lisp/magit-mode.el
* lisp/magit-mode.el (magit--imenu-goto-function): New function.
(magit-mode): Set locally in magit-mode as imenu-default-goto-function.
-------
This new function automatically expands the jumped-to section, as well as its children and ancestors.  Without this function, the section is not automatically expanded, which then requires the user to manually expand the ancestor sections and jump to it again. 
Thanks for your work on Magit!
> Add: (magit--imenu-goto-function) For imenu-default-goto-function

- lisp/magit-diff.el
This patch complements 564cff8a40c2d7c8d4e679f1c7c2974c97f5f149 by also allowing following file renames formatted as follows:
* `foo/{ => bar/baz}/qux/quux.c`
* `foo/{bar/baz => }/qux/quux.c`
> magit-diff-wash-diffstat: Allow empty renames

- lisp/magit-status.el
-------
When using `M-x magit-status-here` in a narrowed buffer, something like this is necessary to visit the corresponding position of the file.
~I thought about using `pcase-let*` instead to avoid having to `widen` twice, but I also didn't want to clutter the diff and `git blame` sessions.~
I changed my mind, `save-restriction` and `widen` might not necessarily be fast.
> magit-status-setup-buffer: Ensure correct position when narrowed

- lisp/git-commit.el
Fixes typo in the original change.
> Correct target of obsolete alias git-commit-known-pseudo-headers

- lisp/magit-section.el
This commit addresses an issue where if you run a command like `persp-switch` which uses `set-window-buffer`, the current buffer is not updated which can cause magit-post-command-hook to emit an error.
> Check current buffer in magit-section-post-command-hook

- lisp/magit-section.el
This pull request renames a variable containing a typo in a warning from function `magit-section--enable-long-lines-shortcuts`.
In this warning, the Emacs variable in question `long-line-threshold` was written as `long-line-threshhold`.
This caused me an issue while killing the variable from the warning and yanking it into the command `describe-variable`.
> Fixed typo in magit-section--enable-long-lines-shortcuts warning

- docs/magit.org
- docs/magit.texi
This pull request applies to docs only; in particular, it applies to only `magit.org`.
In that file I replace:
- "strickly" -> "strictly"
- "stricktly" -> "strictly"
I change this because I find results on Google for "strictly" but not "strick(t)ly"
I ask the maintainers to make `magit.texi`. 
I commit changes only to `magit.org`. I made `magit.texi` with
```shell
make texi
```
I did not commit the resulting `magit-section.texi` or `magit.texi` because the versions I made locally removed the newline at the end of the file, and in the section of `PULL_REQUEST_TEMPLATE` "Do NOT use Github to edit files and create commit messages" I saw a concern about newlines at end of commits. So I was cautious about (a) newlines at the end of doc files and (b) editing the generated files.
Separately I …
> docs only: typo: replace "strick" with "strict"

- docs/magit.org
- docs/magit.texi
The key for `magit-ediff-resolve-all` is wrong in the doc. Instead of `E m` it should be `E M`,
> docs/magit.org: Use correct key E M for magit-ediff-resolve-all

- lisp/magit-section.el
This commit just fixes a missing call to `format` and a typo in `magit-section--enable-long-lines-shortcuts`.
> Fix formatting of magit-show-long-lines-warning

- test/magit-tests.el
`magit-with-test-directory` adds "GIT_AUTHOR_NAME" and "GIT_AUTHOR_EMAIL" to the environment.  However, git-commit also requires the name and e-mail of the committer:
```
$ testdir=$(mktemp -d)
$ cd $testdir
$ git -c init.defaultBranch=main init
Initialized empty Git repository in /tmp/tmp.9kL3SoUfii/.git/
$ GIT_AUTHOR_NAME='A. U. Thor' GIT_AUTHOR_EMAIL=a.u.thor@example.com \
> git commit --allow-empty -m init
Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <aztest@ulthar.dreamlands>) not allowed
$ GIT_AUTHOR_NAME='A. U. Thor' …
```
> test: define committer info for git-commit

- lisp/magit-fetch.el
- lisp/magit-pull.el
git pull and git fetch allow the --force option to force update local branches. From man git-fetch(1):
-f, --force
When git fetch is used with <src>:<dst> refspec it may refuse to
update the local branch as discussed in the <refspec> part
below. This option overrides that check.
Add that option to magit-pull and magit-fetch. Use -F as the suffix to be consistent with magit-push.
> Add --force to magit-pull and magit-fetch

- lisp/magit-section.el
Loading magit bookmarks from a new emacs session uses
`magit--handle-bookmark`.  This provides an autoload to ensure this
works even prior to loading magit.  `magit-bookmark` is also required,
as it implements the necessary generic methods.
See Discussion #5168.
> autoload magit--handle-bookmark and require magit-bookmark

- lisp/magit-diff.el
I find `magit-smerge-keep-all` useful, and I think it would be nice if this command was a little more discoverable by including it in `magit-hunk-section-smerge-map`.
Thanks for all your hard work!
> magit-hunk-section-smerge-map: Add magit-smerge-keep-all

- lisp/magit-files.el
Hi!
Eglot may be activated for buffers visiting blobs, and most LSP servers bail out in that case. So in this commit we remove the activation function from the relevant hook.
Note that when started, Eglot checks and attempts to manage existing buffers as well. However, at that point, buffers visiting blobs have 'buffer-file-name' being nil, and Eglot will ignore them. So we only need to modify the hook instead of advising the function.
This is to achieve the same effect as the advice for 'lsp', introduced in f8353f57.
Thank you!
> Avoid activating Eglot for buffers visiting blobs

- lisp/magit-files.el
Hello!
In Emacs commit [9506b9392e], `define-globalized-minor-mode` was refactored, and in Emacs 30 only the function `MODE-enable-in-buffer` is added to `after-change-major-mode-hook`. So in this PR we remove both the new and the old functions from the hook to avoid activating `diff-hl-mode` for blob buffers.
Thank you!
[9506b9392e]: https://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/emacs-lisp/easy-mmode.el?id=9506b9392e8c3548b769d9951a1c9d4abad9ee21
> magit-revert-rev-file-buffer: Adapt to upstream changes in Emacs 30

- CHANGELOG
- lisp/magit-process.el
Currently, if you set `magit-tramp-pipe-stty-settings` to `'pty` it will bind `tramp-pipe-stty-settings` to its own symbol value. But if tramp has not been loaded yet this will result in referencing a void variable. We fix this by checking if the variable is bound before referencing it. 
`(setq magit-tramp-pipe-stty-settings 'pty)`
call `magit-status`.
> magit-start-process: Handle tramp-pipe-stty-settings being unbound

- lisp/magit-extras.el
If the current section type is not one of
'(branch commit module-commit tag)
the intention here is to just copy the raw section value, but this was not being done. Instead, `magit-section-case` was unfortunately interpreting the `(kill-new (message ...))` expression as a list of section types. Whoops!
Use the default case to correct this error.
> magit-copy-section-value: fix default case

- lisp/magit-clone.el
- lisp/magit-remote.el
This update removes the redundant "or" from the prompt messages.
The `magit-read-char-case` macro has been updated to automatically format prompt messages in natural English and correctly add "or" before the last entry.  However, this change led to some prompt messages containing duplicated "or" words.  For instance, the prompt for the `magit-clone` command previously displayed:
> Clone from [u]rl or name, [p]ath, [l]ocal url, or **or** [b]undle
This update addresses that issue by removing the redundant "or."
> Fix magit-read-char-case macro usages

- lisp/git-commit.el
The git-commit--trailer-regexp regex is written so that either groups 1 and 2 will match or groups 3 and 4 will match, but it is impossible for all 4 groups to match.
This patch updates the font-lock regex checker to be lax about whether or not the group matched. Without this patch we have errors like:
Error during redisplay: (jit-lock-function 77) signaled (error "No match 3 in highlight (3 'git-commit-trailer-token)")
See #5317
> git-commit: make trailer regex matches lax

- lisp/magit-section.el
Often I find I'd like to see changes in some of the staged files. Changing levels one by one is time consuming and changing level for entire staged section is too verbose. This QoL improvement makes this task way faster.
> magit-section-show-level: Support using region of sections

- .github/PULL_REQUEST_TEMPLATE
- docs/magit.org
- docs/magit.texi
- lisp/magit-diff.el
From my reading, the existing documentation for `magit-diff-visit-file` accidentally copies a line from `magit-diff-visit-worktree-file`, specifically "This commands [sic] visits the worktree version of the appropriate file". 
This PR deletes that sentence and also combines the existing "This command..." sentence with the following paragraph to be consistent with the other commands/options in the same section.
> manual: Remove inaccurate sentence about magit-diff-visit-file
